### ISSUE TITLE
The local replica is not properly recognized by the plugin and fails to sync changes if `**/*.git` added to the ignored patterns

### ISSUE THREAD

**Issue by e-zz** [iamhyc/Overleaf-Workshop#101]
### Describe the bug
when I  closing it with `ctrl+k f` and start vscode from the directory of the replica folder, somehow the plugin can not properly recognize the replica
- The cloud icon is gone
   ![image](https://github.com/iamhyc/Overleaf-Workshop/assets/37920155/4a6399ef-879c-46e1-9c6f-7a670cddc8c4)
- The `.overleaf` folder is still in the folder, and I checked there's nothing wrong with the content of  `.overleaf/settings.json`.
-  I can still see the indicator for my collaborator's cursor (actually me on the website). But it freezes and never moves. Here is the indicator I mentioned
  ![image](https://github.com/iamhyc/Overleaf-Workshop/assets/37920155/ed5fb731-6cf9-46f1-8670-beba1366e3e6)

- Local changes are not synced to overleaf automatically. 
    - Manual syncing is impossible since here we lost our cloud icon. Even the "upload to overleaf" option in the Invisible mode is not accessible now. 
   ![image](https://github.com/iamhyc/Overleaf-Workshop/assets/37920155/22a77f8f-fff7-47dc-896d-dab41969942a)
- Also, it's impossible to open the replica again from plugin's Hosts view, because the path is somehow invalid
  ![image](https://github.com/iamhyc/Overleaf-Workshop/assets/37920155/a6593a2f-3ba1-4e7a-8aa3-97f893ed68fe)
  ![image](https://github.com/iamhyc/Overleaf-Workshop/assets/37920155/5fdbf8ea-8a02-4a24-a64a-9980f404f13f)
- The only way to enter that replica I found till now, is to recreate a new replica at the same place, then everything is fine in the replica just created. Thankfully the plugin doesn't overwrite the folder (maybe because of the `.overleaf` existent there?)

### Expected behavior
> A clear and concise description of what you expected to happen.

### How To Reproduce
Open a project and create a local replica. Close the replica in vscode and reopen it. Make changes to test syncing

### Environment
 - **Overleaf Workshop Extension version**: 0.9.1
 - **VS Code version**: 1.85.1
 - **Overleaf Edition**: Official

### [Optional] Developer Logs
> If applicable, please paste the logs inside the details section below.
> Please find the logs via: Title bar **"Help"** > **"Toggle Developer Tools"** > **"Console"**.

<details>
  ...
</details>

**Comment by iamhyc** [comment]
Hi @e-zz , please also provide the developer logs. I think there should be some clues there.

**Comment by e-zz** [comment]
Hi,

I tried many things wierd that I did to the problematic replica. finaly I found the cause is I add  [:](f)
- use the command `overleaf workshop: configure source control` in vscode command palatte
- choose a local replica to open and wait until the cloud icon appears in the bottom status bar
- And use the `overleaf workshop: configure source control` command again,  choose the replica, and click `configure the sync ignore patterns`
   ![image](https://github.com/iamhyc/Overleaf-Workshop/assets/37920155/0c11624c-b65c-49dd-b177-181218f6479e)
- Add `**/*.git` the pattern
   ![image](https://github.com/iamhyc/Overleaf-Workshop/assets/37920155/edbfe4fc-31c9-4992-816f-0f6890e10add)
- close the replica folder, then 
    - reopen it in the plugin's Hosts view 
    - or directly open the replica folder in vscode

Then we will see the path of the replica is invalid 
![image](https://github.com/iamhyc/Overleaf-Workshop/assets/37920155/fb17e890-f114-4aa9-9b81-4583a9783cf9)

and the cloud icon is always missing
![image](https://github.com/iamhyc/Overleaf-Workshop/assets/37920155/258663d3-06a9-4e26-bc32-49d1d4844cc5)

I guess it's related to the source control mechanism because it's caused by the ignored `*.tex.git` files. So it might not be a bug, but just a wrong user behavior

I have no idea why this prevents the plugin from recognizing the replica or syncing changes. But I tried the procedure few times. Each time the problem recurs after adding the ignore pattern `**/*.git`.

Hope this helps!

**Comment by e-zz** [comment]
+

> > Hi @e-zz , please also provide the developer logs. I think there should be some clues there.
> 
> I have also encountered the same issue. Can you please tell me how to delete the local replica named '/[object Object]'?

Just create the replica in the same place again, then the path can be fixed I think.
- Open the project and use the command  `overleaf workshop: configure source control`, then you could create replica again.

**Comment by dawn-ech** [comment]
> > > Hi @e-zz , please also provide the developer logs. I think there should be some clues there.
> > 
> > 
> > I have also encountered the same issue. Can you please tell me how to delete the local replica named '/[object Object]'?
> 
> Just create the replica in the same place again, then the path can be fixed I think.
> 
> * Open the project and use the command  `overleaf workshop: configure source control`, then you could create replica again.

I tried this approach. And later, when I opened it locally, I could see that there were two local replicas. The local changes are not syncing. After a while, the local replica that was just created disappeared again.

**Comment by e-zz** [comment]
I noticed again deletion of some TeX files.

> > > > Hi @e-zz , please also provide the developer logs. I think there should be some clues there.
> > > 
> > > 
> > > I have also encountered the same issue. Can you please tell me how to delete the local replica named '/[object Object]'?
> > 
> > 
> > Just create the replica in the same place again, then the path can be fixed I think.
> > 
> > * Open the project and use the command  `overleaf workshop: configure source control`, then you could create replica again.
> 
> I tried this approach. And later, when I opened it locally, I could see that there were two local replicas. The local changes are not syncing. After a while, the local replica that was just created disappeared again.

Sorry, then I don't know what's the solution in your case. If you just wannn get rid of `/[object/object]`, maybe you could also try reintsalling the plugin?

**Comment by e-zz** [comment]
@iamhyc  Another thing is the "auto-deletetion" I noticed in the begining of our discussion #100 . So it might be another problem caused by `*.git` files.
If we remove the sync ignore pattern `**/*.git`, then `main.tex" will be removed silently after the `main.tex.git` is removed locally or from the website.

**Comment by iamhyc** [comment]
@e-zz Thanks for the information!

Please use the temporary extension [here](https://github.com/iamhyc/Overleaf-Workshop/actions/runs/7946010409?pr=102), which should solve the `/[object Object]` bug.

As for the file repeated creation/deletion, please let me know if you can reproduce it via certain operations. Thank you!

**Comment by iamhyc** [comment]
> > Hi @e-zz , please also provide the developer logs. I think there should be some clues there.
> 
> I have also encountered the same issue. Can you please tell me how to delete the local replica named '/[object Object]'?

The abnormal file path should be automatically removed. If not, please open the project normally (not locally), and remove it in `overleaf workshop: configure source control`.

**Comment by e-zz** [comment]
> @e-zz Thanks for the information!
> 
> Please use the temporary extension [here](https://github.com/iamhyc/Overleaf-Workshop/actions/runs/7946010409?pr=102), which should solve the `/[object Object]` bug.
> 
> As for the file repeated creation/deletion, please let me know if you can reproduce it via certain operations. Thank you!

It works perfectly with `**/**.git` ignore pattern now. Thanks for the quick fix!
As for the unexpected creation/deletion, I will open an issue if it still happens.
