### ISSUE TITLE
[Invisible mode//Local replica] Faill to initiate invisible mode in a replica with too many files 

### ISSUE THREAD

**Issue by e-zz** [iamhyc/Overleaf-Workshop#103]
### Describe the bug
When entering invisible mode, the plugin push and pull files in the directory. As a side effect, the files are modfied.

#### Files are modified
**In DevTools**: files are pushed and pulled
<img src="https://github.com/iamhyc/Overleaf-Workshop/assets/37920155/bbfdea38-2ee1-44ab-bfbf-43fca4f0da7a" alt="In DevTools" width="600" >

**In overleaf history**: files are modified (deleted and then created)

<img src="https://github.com/iamhyc/Overleaf-Workshop/assets/37920155/fc805bba-0737-43d9-a058-025170a2ef27" alt="On overleaf" width="300" >

And on my pc, in the folder `pic`, files are all modified

<img src="https://github.com/iamhyc/Overleaf-Workshop/assets/37920155/bfe8e6f9-3b0a-46c5-b7c6-8eaae596016d" alt="On overleaf" width="600" >

#### Some files are broken
And in the end, one could see from the pic above that some files are empty
But no worries. It can be all recovered by simply reopening the replica if the replica hasn't been synced yet.

### Connection Limit
There is a connection limit set by overleaf, which interrupts the inivisible mode and cause the problem:

![image](https://github.com/iamhyc/Overleaf-Workshop/assets/37920155/f23d546b-2d90-41f3-9a9e-872bc3128a7c)
Once we reach the limit, any further push/pull request will be refused and the initialization of invisible mode will be disrupted. 

What makes it even worse is that when disconnected, the plugin seems to keep requesting new connection to overleaf.

### Expected behavior
The invisible mode should work in a way similar to the non-visible mode in the sense that local files should not be touched by the plugin.

### How To Reproduce
Create a replica with a lot of files. I cannot give an exact number. But for my problematic replica, there are 41 PDFs in the `pic` folder shown above.

### Environment
 - **Overleaf Workshop Extension version**: 0..9.2
 - **VS Code version**: 1.85.1
 - **Overleaf Edition**: Official

**Comment by iamhyc** [comment]
Hi @e-zz , please help check if the latest temporary extension [here](https://github.com/iamhyc/Overleaf-Workshop/actions/runs/7999090905?pr=102) solves the abnormality.

The root cause is that when every time the extension re-connect to the server, one duplicated "local replica" is created and the previous one is not disposed.

**Comment by e-zz** [comment]
> Hi @e-zz , please help check if the latest temporary extension [here](https://github.com/iamhyc/Overleaf-Workshop/actions/runs/7999090905?pr=102) solves the abnormality.
> 
> The root cause is that when every time the extension re-connect to the server, one duplicated "local replica" is created and the previous one is not disposed.

Much appreciated. Yes it does. 
Now the local files are intact after switching to the invisible mode.
