### ISSUE TITLE
[Feature Request] Multiple Files Version Comparison

### ISSUE THREAD

**Issue by QianrenLi** [iamhyc/Overleaf-Workshop#105]
### Disclaimer
> Please make sure all the items below is checked (i.e., prefixed with "- [x]")
- [x] The request feature has not been addressed in the [feature request list](https://github.com/iamhyc/Overleaf-Workshop/issues?q=is%3Aissue+label%3A%22feature+request%22+).
- [x] The design of the feature does not require detailed discussion, or existing discussion with drawn conclusion can be found in [Discussions Area](https://github.com/iamhyc/Overleaf-Workshop/discussions) at: [paste the link here]

### Motivation
> Please give strong enough reason(s) why the feature is demanded.
- Current version comparison compares the changes in the same file and since history is opened along with file individually, comparing multiple file changing in different versions requires searchs the same version number manually which might be difficult sometimes especially when the number of version change is large.

### Feature Description
> A clear and concise description of what you want to happen under what circumstance.
- It is capable to select multiple files when comapring the difference between different versions.

### Informations
It seems vscode has implemented some APIs for multiple file compariosn:
- https://github.com/microsoft/vscode/blob/d0e118cb72ead940697f3f84ff5cbe1a859f8fc7/src/vs/workbench/api/common/extHostApiCommands.ts#L435
- https://github.com/microsoft/vscode-pull-request-github/blob/main/src/github/pullRequestModel.ts#L1163
- https://github.com/microsoft/vscode/issues/179000
 
Hope these imformation is helpful to this feature.

### [Optional] Additional context
> Please strike out any inappropriate items below. If you are not aware of the difference, please ignore this section.
- **Applicable Overleaf Edition**: Official / Community / Enterprise (Server Pro)
- **Applicable Extension Range**: Desktop Extension / Web Extension

**Comment by iamhyc** [comment]
wait for #107 merged cause we gonna use `vscode.changes` for multi-file diff.
