### ISSUE TITLE
How can I loggin my latex?

### ISSUE THREAD

**Issue by risingClouds** [iamhyc/Overleaf-Workshop#11]
I'm so delighted for this extension that I have been looking forward to.But I can't understand the reference docs. I don't know how  can i obtain the overleaf server address? Can you offer a detail? Best wish!

**Comment by iamhyc** [comment]
The "overleaf server address" is the web address to your overleaf/sharelatex service, e.g. "http://overleaf.org".

Currently, we only support: 1) email/password login, 2) open-source overleaf/sharelatex version with captcha disabled.

For example, the following login is not supported:
- login to `overleaf.com` with email/password (cause captcha check is enabled)
- SSO login to any overleaf/sharelatex service.

**Comment by risingClouds** [comment]
thank you for your reply, but there's some problem on&nbsp;captcha when I login with email/password.&nbsp;

Best Wish!
----
&nbsp;


木华
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年9月18日(星期一) 晚上6:22
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [iamhyc/Overleaf-Workshop] How can I loggin my latex? (Issue #11)





 
The "overleaf server address" is the web address to your overleaf/sharelatex service, e.g. "http://overleaf.org".
 
Currently, we only support: 1) email/password login, 2) open-source overleaf/sharelatex version with captcha disabled.
 
For example, the following login is not supported:
  
login to overleaf.com with email/password (cause captcha check is enabled)
 
SSO login to any overleaf/sharelatex service.

**Comment by iamhyc** [comment]
Anyway, if your service have captcha check enabled, the login is not supported by this extension. This problem may not be solved in the near future development.

If you have no other question, I shall close this issue.

**Comment by risingClouds** [comment]
I have no questions. thanks


&nbsp;


木华
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年9月18日(星期一) 晚上6:45
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [iamhyc/Overleaf-Workshop] How can I loggin my latex? (Issue #11)





 
Anyway, if your service have captcha check enabled, the login is not supported by this extension. This problem may not be solved in the near future development.
 
If you have no other question, I shall close this issue.
