### ISSUE TITLE
[Feature Request] Does this work only with a Premium Membership

### ISSUE THREAD

**Issue by gudlot** [iamhyc/Overleaf-Workshop#119]
Hi,
thank you for the nice idea.
It is not clear to me if this plugin works only if one has an Overleaf Premium membership.
Thank you for your clarification.  Sorry if I have overlooked it.

**Comment by iamhyc** [comment]
No, it is originally designed for the open-source Overleaf version, and now it also supports some premium features.

**Comment by gudlot** [comment]
Ok, super. I will try to get it working.

**Comment by iamhyc** [comment]
> Ok, super. I will try to get it working.

If you have trouble in how to use it, please refer to the wiki:

https://github.com/iamhyc/Overleaf-Workshop/blob/master/docs/wiki.md
