### ISSUE TITLE
Cookie log in problem, need OA

### ISSUE THREAD

**Issue by 0xTong** [iamhyc/Overleaf-Workshop#130]
### Describe the bug
> A clear and concise description of what the bug is.

### Expected behavior
> A clear and concise description of what you expected to happen.
I want to use the cookie to login but I can't login, my cookies look a little bit special 
oa=1; GCLB=CKfmlIrPlqm1rgEQAw; overleaf_session2=s%3AT7ra_DLxZdvlQQVk8TnqbZSlY9WBb62.NYUJFxZmxU8fD%2BPcdIhVZkLQH1t7J5aptRDc4%2FYJEoc

### How To Reproduce
> Detailed steps to reproduce the behavior.

### Environment
 - **Overleaf Workshop Extension version**: [e.g., 0.12.1]
 - **VS Code version**: [e.g. 1.85.0]
 - **Overleaf Edition**: Enterprise (Server Pro)

**Comment by iamhyc** [comment]
Hi, I remove the `overleaf_session2=...` part for you in case of cookie leak.

And you only need to copy that part to login :)
