### ISSUE TITLE
Random error notifications

### ISSUE THREAD

**Issue by pramodhrachuri** [iamhyc/Overleaf-Workshop#131]
### Describe the bug
> A clear and concise description of what the bug is.
I sometimes get an error notification from vscode intermittently. It doesn't stop any functionality, but it is annoying. I have pasted the screenshot of the notification below

![image](https://github.com/iamhyc/Overleaf-Workshop/assets/13718503/3beed3e4-8397-4c7b-a0c0-986ca392a8a5)

### Expected behavior
> A clear and concise description of what you expected to happen.
No intermittent appearance of the error. 

### How To Reproduce
> Detailed steps to reproduce the behavior.
Just typing text.

### Environment
 - **Overleaf Workshop Extension version**:  v0.12.1
 - **VS Code version**: 1.89.0
 - **Overleaf Edition**: Official free

Error as text below 
```
500: <!DOCTYPE html><html lang="en"><head><title>Something went wrong</title><link rel="icon" href="/favicon.ico"><link rel="stylesheet" href="https://cdn.overleaf.com/stylesheets/main-style-862a96de03443827634c.css"></head></html><body class="full-height"><main class="content content-alt full-height" id="main-content"><div class="container full-height"><div class="error-container full-height"><div class="error-details"><p class="error-status">Something went wrong, sorry.</p><p class="error-description">Our staff are probably looking into this, but if it continues, please check our status page at
<a href="http://status.overleaf.com">status.overleaf.com</a>
or contact us at
<a href="mailto:support@overleaf.com">support@overleaf.com</a>.</p><p class="error-actions"><a class="error-btn" href="/">Home</a></p></div></div></div></main></body>
```

Great project, BTW! Very useful

**Comment by pramodhrachuri** [comment]
I think this error occurs if I edit a tex file when a collaborator is compiling to PDF on overleaf web at the same time. I need to confirm this though

**Comment by iamhyc** [comment]
Hi @pramodhrachuri , thanks for the feedback!

The 500 error should be a notification of failed HTTP request. Please try to attach the error logs (red ones) when it popped up.
> Please find the logs via: Title bar **"Help"** > **"Toggle Developer Tools"** > **"Console"**.

And you can turn off "Overleaf Workshop Compile on Save" in vscode settings to see if the problem solved.

**Comment by pramodhrachuri** [comment]
Thanks for the response. Turning off "Overleaf Workshop Compile on Save" helped.
However, I think it unsurfaced another bug.

I have autosave turned on in VS Code. When I make changes to tex and immediately press compile, the compiled version doesn't show the new changes. This is explainable- VS Code takes a while when autosaving. If I press compile before the autosave finishes, overleaf/latex is looking at an older version for compiling. I don't think this is the case with other programming languages.

A probable fix is- save before running the compiler.

Let me know your thoughts. Shall I create another issue about this?

**Comment by iamhyc** [comment]
Hi @pramodhrachuri , I am not sure whether the two thing, "compile refers to elder version" and "random error when compile collides", are related or not. I think posting a new issue is better.

> A probable fix is- save before running the compiler.

Yes, I think I overlooked it. The compile should wait for all the dirty files saved and then begin.

**Comment by iamhyc** [comment]
And for the origin issue here, I think we may just ignore the error cause we have nothing to do about it.

Let me know if you have any better ideas.

**Comment by pramodhrachuri** [comment]
Hey @iamhyc ,
Ignoring the errors makes sense. I, too, don't believe that Overleaf Workshop has anything to do with it.

I will create a new issue about the other issue and closing this one
