### ISSUE TITLE
Created Files will be unexpectedly deleted

### ISSUE THREAD

**Issue by sleepymalc** [iamhyc/Overleaf-Workshop#134]
### Describe the bug
> A clear and concise description of what the bug is.

Firstly, I have a workflow that will automatically export LaTeX-compatible figure files created by Inkscape (including `xxx.svg`, `xxx.pdf`, `xxx.pdf_tex`). It seems like when using local environment with Overleaf-Workshop, since the extension is trying to not uploading all random files, whenever my workflow is working (i.e., exporting files to some directory under the project), after a few seconds, the extension will delete both `xxx.svg` and `xxx.pdf`. I consider this as a bug since only files that is produced after compilation should be discarded by this extension (e.g., `xxx.bbl`).

### Expected behavior
> A clear and concise description of what you expected to happen.

Not deleting these files uploaded by the user.

### How To Reproduce
> Detailed steps to reproduce the behavior.

I tried to copy and paste a `pdf` file without using VS Code, and after a second it's deleted. I guess this reproduces the problem.

### Environment
 - **Overleaf Workshop Extension version**: 0.12.1
 - **VS Code version**: 1.88.1
 - **Overleaf Edition**: Official

### [Optional] Developer Logs
> If applicable, please paste the logs inside the details section below.
> Please find the logs via: Title bar **"Help"** > **"Toggle Developer Tools"** > **"Console"**.

<details>

console.ts:137 [Extension Host] 5/16/2024, 6:32:01 PM [push] update "/Test/Figures/test.pdf"
console.ts:137 [Extension Host] 5/16/2024, 6:32:24 PM [pull] delete "/Test/Figures/Diploma.pdf"
console.ts:137 [Extension Host] 5/16/2024, 6:32:29 PM [pull] delete "/Test/Figures/Diploma (Copy).pdf"
console.ts:137 [Extension Host] 5/16/2024, 6:32:34 PM [pull] delete "/Test/Figures/test.pdf"

</details>

### Additional Information
Here's other information that might help: basically the sync between the local and Overleaf server is inconsistent. I observe that when I past the `xxx.pdf` to my local project folder without using VS Code, it actually syncs to the Overleaf server (hence the online project). However, later when it's deleted from my local environment, `xxx.pdf` on the Overleaf server is still there. If I close VS Code and re open this project (using local edit again), it'll download the "deleted" `xxx.pdf` from Overleaf server.

**Comment by iamhyc** [comment]
> console.ts:137 [Extension Host] 5/16/2024, 6:32:01 PM [push] update "/Test/Figures/test.pdf"
> console.ts:137 [Extension Host] 5/16/2024, 6:32:24 PM [pull] delete "/Test/Figures/Diploma.pdf"
> console.ts:137 [Extension Host] 5/16/2024, 6:32:29 PM [pull] delete "/Test/Figures/Diploma (Copy).pdf"
> console.ts:137 [Extension Host] 5/16/2024, 6:32:34 PM [pull] delete "/Test/Figures/test.pdf"

If the attached log is complete, it seems weird that server want to apply(pull) delete action, while there is no push action before.

Can you see what the time when the deleted files were pushed to the server?

**Comment by sleepymalc** [comment]
Hmm, I'm copy-pasting random files (in this case my Diploma lol) around and decide to make a `test.pdf` afterwards. Seems like some lagged action is performed after I switched to `test.pdf`. Let's me try this again and report a full-set of log.

**Comment by iamhyc** [comment]
I see. I will try to figure out why and fix it later.

**Comment by iamhyc** [comment]
Hi @sleepymalc , please help test the temporary extension here:

https://github.com/iamhyc/Overleaf-Workshop/actions/runs/9116597812

If there is no more problem, I will have the changes included in the next release.

**Comment by iamhyc** [comment]
well, that is weird. I cannot reproduce the situation in my example project.

I tried (in the local folder, not in vscode), and nothing wrong happened.
- copy multiple files
- overwrite the files with same name, plus one new file
- create a folder, move all the files into it

----
<details>
5/17/2024, 7:50:49 AM [push] update "/temp.md"
5/17/2024, 7:50:49 AM [push] update "/test.pdf"
5/17/2024, 7:50:49 AM [push] update "/test.vsd"
5/17/2024, 7:51:55 AM [push] update "/331323428-f59e36ef-ceae-4905-90f5-aafd3124a6d7.mov"
5/17/2024, 7:52:33 AM [push] update "/新建文件夹"
2
5/17/2024, 7:52:34 AM [pull] update "/新建文件夹"
5/17/2024, 7:52:35 AM [push] delete "/新建文件夹"
5/17/2024, 7:52:35 AM [push] update "/test"
2
5/17/2024, 7:52:35 AM [pull] update "/test"
5/17/2024, 7:52:42 AM [push] delete "/temp.md"
5/17/2024, 7:52:42 AM [push] delete "/test.pdf"
5/17/2024, 7:52:42 AM [push] delete "/test.vsd"
5/17/2024, 7:52:42 AM [push] delete "/331323428-f59e36ef-ceae-4905-90f5-aafd3124a6d7.mov"
5/17/2024, 7:52:42 AM [push] update "/test/temp.md"
5/17/2024, 7:52:42 AM [push] update "/test/test.vsd"
5/17/2024, 7:52:42 AM [push] update "/test/test.pdf"
5/17/2024, 7:52:42 AM [push] update "/test/331323428-f59e36ef-ceae-4905-90f5-aafd3124a6d7.mov"
</details>

**Comment by iamhyc** [comment]
The attached log is also weird. Anyway, I have tried to re-generate the extension, please try again and start with a small project firstly.
https://github.com/iamhyc/Overleaf-Workshop/actions/runs/9116597812

**Comment by iamhyc** [comment]
Yes, I think you did nothing wrong, but I just cannot reproduce it.

I will try to find someone else to test for us.

**Comment by sleepymalc** [comment]
From my knowledge of the workflow I use for auto-exporting these figures, a potential reason is that the workflow relies on `fswatch`, which will monitor the file system. Not sure whether this is the issue.

**Comment by iamhyc** [comment]
> From my knowledge of the workflow I use for auto-exporting these figures, a potential reason is that the workflow relies on `fswatch`, which will monitor the file system. Not sure whether this is the issue.

The sync also relies on vscode fswatch to monitor the changes, but I am not sure if they interfere with each other.

At least the test on Windows with local files copy/move works correctly now .

**Comment by sleepymalc** [comment]
I think sometimes it works fine, but sometimes it doesn't. The interference between `fswatch` can be the problem then.

**Comment by iamhyc** [comment]
> I think sometimes it works fine, but sometimes it doesn't. The interference between `fswatch` can be the problem then.

if that is the case, please let me know how to reproduce it. 

And I wonder if the workflow causes extra "delete action" when update the file. maybe the delete action is not handled properly now. I will take a look ata it later.

**Comment by sleepymalc** [comment]
I have some new observations: basically whenever I update my figures, my workflow will export them once again, causing some over-written. And I think this will trigger some delete commands (base on the log)
<img width="492" alt="image" src="https://github.com/iamhyc/Overleaf-Workshop/assets/60427058/7b5492be-8abc-4ff6-b106-a88083a614a7">
While I'm not sure whether this is really the cause, but if over-written actually triggers a delete, then it makes sense as this will cause interference issues between the file system on the Overleaf server and the local file system. 

I'm really not sure how to reproduce this, but here's one more observation: if you see my previous demo, this warning pops up:
<img width="329" alt="image" src="https://github.com/iamhyc/Overleaf-Workshop/assets/60427058/5eb5118b-ddb8-4547-b50f-005d61531ee0">
I found out that this only happens when the file system on the Overleaf server thinks the pasted files already exists, i.e., I'm pasting a redundant file (in Overleaf server's perspective). So I guess some interference and mis-sync is happening.

**Comment by iamhyc** [comment]
@sleepymalc Thank you. The demos are very clear. I find it interesting that the "pdf file delete" is initiated from overleaf server firstly.

I have update the temporary extension with file hash information included. Please help test and attach the log. We need more information to figure out why.

https://github.com/iamhyc/Overleaf-Workshop/actions/runs/9123020301

**Comment by sleepymalc** [comment]
Okay, this is the new demo:

https://github.com/iamhyc/Overleaf-Workshop/assets/60427058/1bac7c33-47bb-43d4-bcaf-f17405ff4dc5

With the log attached:

<details>

console.ts:137 [Extension Host] 5/17/2024, 1:50:13 PM [push] update "/Figures/test.svg" -1 --> 1972868926
console.ts:137 [Extension Host] 5/17/2024, 1:50:13 PM [push] update "/Figures/test.svg"
console.ts:137 [Extension Host] 5/17/2024, 1:50:13 PM [push] update "/Figures/test.pdf" -1 --> 1924242771
console.ts:137 [Extension Host] 5/17/2024, 1:50:13 PM [push] update "/Figures/test.pdf"
console.ts:137 [Extension Host] 5/17/2024, 1:50:13 PM [push] update "/Figures/test.pdf_tex" -1 --> -2092866401
console.ts:137 [Extension Host] 5/17/2024, 1:50:13 PM [push] update "/Figures/test.pdf_tex"
console.ts:137 [Extension Host] --> Run Command: inkscape-figures edit "${fileDirname}/Figures/"
console.ts:137 [Extension Host] 5/17/2024, 1:50:22 PM [push] update "/Figures/test.svg" 1972868926 --> 1620541927
console.ts:137 [Extension Host] 5/17/2024, 1:50:22 PM [push] update "/Figures/test.svg"
console.ts:137 [Extension Host] 5/17/2024, 1:50:23 PM [push] update "/Figures/test.pdf" 1924242771 --> -922936231
console.ts:137 [Extension Host] 5/17/2024, 1:50:23 PM [push] update "/Figures/test.pdf"
console.ts:137 [Extension Host] 5/17/2024, 1:50:23 PM [push] update "/Figures/test.pdf_tex" -2092866401 --> 1703342341
console.ts:137 [Extension Host] 5/17/2024, 1:50:23 PM [push] update "/Figures/test.pdf_tex"
console.ts:137 [Extension Host] 5/17/2024, 1:50:23 PM [pull] delete "/Figures/test.pdf_tex" 1703342341 --> -1
console.ts:137 [Extension Host] 5/17/2024, 1:50:23 PM [pull] delete "/Figures/test.pdf_tex"
console.ts:137 [Extension Host] 5/17/2024, 1:50:23 PM [pull] update "/Figures/test.pdf_tex" -1 --> 1703342341
console.ts:137 [Extension Host] 5/17/2024, 1:50:23 PM [pull] update "/Figures/test.pdf_tex"
console.ts:137 [Extension Host] 5/17/2024, 1:50:23 PM [pull] update "/Figures/test.pdf_tex" 1703342341 --> 0
console.ts:137 [Extension Host] 5/17/2024, 1:50:23 PM [pull] update "/Figures/test.pdf_tex"
console.ts:137 [Extension Host] 5/17/2024, 1:50:23 PM [pull] delete "/Figures/test.svg" 1620541927 --> -1
console.ts:137 [Extension Host] 5/17/2024, 1:50:23 PM [pull] delete "/Figures/test.svg"
console.ts:137 [Extension Host] 5/17/2024, 1:50:23 PM [pull] update "/Figures/test.svg" -1 --> 0
console.ts:137 [Extension Host] 5/17/2024, 1:50:23 PM [pull] update "/Figures/test.svg"
console.ts:137 [Extension Host] 5/17/2024, 1:50:23 PM [pull] update "/Figures/test.svg"
console.ts:137 [Extension Host] 5/17/2024, 1:50:23 PM [push] delete "/Figures/test.svg"
console.ts:137 [Extension Host] 5/17/2024, 1:50:23 PM [push] delete "/Figures/test.pdf_tex"
console.ts:137 [Extension Host] 5/17/2024, 1:50:24 PM [pull] delete "/Figures/test.pdf" -922936231 --> -1
console.ts:137 [Extension Host] 5/17/2024, 1:50:24 PM [pull] delete "/Figures/test.pdf"
console.ts:137 [Extension Host] 5/17/2024, 1:50:24 PM [pull] update "/Figures/test.pdf" -1 --> -922936231
console.ts:137 [Extension Host] 5/17/2024, 1:50:24 PM [pull] update "/Figures/test.pdf"
notificationsAlerts.ts:42 404: <!DOCTYPE html><html lang="en"><head><title>Page Not Found - Overleaf, Online LaTeX Editor</title><meta name="twitter:title" content="Page Not Found"><meta name="og:title" content="Page Not Found"><meta name="description" content="An online LaTeX editor that’s easy to use. No installation, real-time collaboration, version control, hundreds of LaTeX templates, and more."><meta itemprop="description" content="An online LaTeX editor that’s easy to use. No installation, real-time collaboration, version control, hundreds of LaTeX templates, and more."><meta itemprop="image" content="https://cdn.overleaf.com/img/ol-brand/overleaf_og_logo.png"><meta name="image" content="https://cdn.overleaf.com/img/ol-brand/overleaf_og_logo.png"><meta itemprop="name" content="Overleaf, the Online LaTeX Editor"><meta name="twitter:card" content="summary"><meta name="twitter:site" content="@overleaf"><meta name="twitter:description" content="An online LaTeX editor that’s easy to use. No installation, real...
c @ notificationsAlerts.ts:42
(anonymous) @ notificationsAlerts.ts:28
y @ event.ts:1156
z @ event.ts:1167
fire @ event.ts:1191
addNotification @ notifications.ts:228
notify @ notificationService.ts:253
(anonymous) @ mainThreadMessageService.ts:86
f @ mainThreadMessageService.ts:51
$showMessage @ mainThreadMessageService.ts:45
S @ rpcProtocol.ts:458
Q @ rpcProtocol.ts:443
M @ rpcProtocol.ts:373
L @ rpcProtocol.ts:299
(anonymous) @ rpcProtocol.ts:161
y @ event.ts:1156
fire @ event.ts:1187
fire @ ipc.net.ts:650
q.onmessage @ localProcessExtensionHost.ts:376
console.ts:137 [Extension Host] 5/17/2024, 1:50:24 PM [pull] update "/Figures/test.pdf" -922936231 --> 0
console.ts:137 [Extension Host] 5/17/2024, 1:50:24 PM [pull] update "/Figures/test.pdf"
notificationsAlerts.ts:42 404: <!DOCTYPE html><html lang="en"><head><title>Page Not Found - Overleaf, Online LaTeX Editor</title><meta name="twitter:title" content="Page Not Found"><meta name="og:title" content="Page Not Found"><meta name="description" content="An online LaTeX editor that’s easy to use. No installation, real-time collaboration, version control, hundreds of LaTeX templates, and more."><meta itemprop="description" content="An online LaTeX editor that’s easy to use. No installation, real-time collaboration, version control, hundreds of LaTeX templates, and more."><meta itemprop="image" content="https://cdn.overleaf.com/img/ol-brand/overleaf_og_logo.png"><meta name="image" content="https://cdn.overleaf.com/img/ol-brand/overleaf_og_logo.png"><meta itemprop="name" content="Overleaf, the Online LaTeX Editor"><meta name="twitter:card" content="summary"><meta name="twitter:site" content="@overleaf"><meta name="twitter:description" content="An online LaTeX editor that’s easy to use. No installation, real...
c @ notificationsAlerts.ts:42
(anonymous) @ notificationsAlerts.ts:28
y @ event.ts:1156
z @ event.ts:1167
fire @ event.ts:1191
addNotification @ notifications.ts:228
notify @ notificationService.ts:253
(anonymous) @ mainThreadMessageService.ts:86
f @ mainThreadMessageService.ts:51
$showMessage @ mainThreadMessageService.ts:45
S @ rpcProtocol.ts:458
Q @ rpcProtocol.ts:443
M @ rpcProtocol.ts:373
L @ rpcProtocol.ts:299
(anonymous) @ rpcProtocol.ts:161
y @ event.ts:1156
fire @ event.ts:1187
fire @ ipc.net.ts:650
q.onmessage @ localProcessExtensionHost.ts:376
console.ts:137 [Extension Host] 5/17/2024, 1:50:24 PM [push] delete "/Figures/test.pdf"
notificationsAlerts.ts:42 404: <!DOCTYPE html><html lang="en"><head><title>Page Not Found - Overleaf, Online LaTeX Editor</title><meta name="twitter:title" content="Page Not Found"><meta name="og:title" content="Page Not Found"><meta name="description" content="An online LaTeX editor that’s easy to use. No installation, real-time collaboration, version control, hundreds of LaTeX templates, and more."><meta itemprop="description" content="An online LaTeX editor that’s easy to use. No installation, real-time collaboration, version control, hundreds of LaTeX templates, and more."><meta itemprop="image" content="https://cdn.overleaf.com/img/ol-brand/overleaf_og_logo.png"><meta name="image" content="https://cdn.overleaf.com/img/ol-brand/overleaf_og_logo.png"><meta itemprop="name" content="Overleaf, the Online LaTeX Editor"><meta name="twitter:card" content="summary"><meta name="twitter:site" content="@overleaf"><meta name="twitter:description" content="An online LaTeX editor that’s easy to use. No installation, real...
c @ notificationsAlerts.ts:42
(anonymous) @ notificationsAlerts.ts:28
y @ event.ts:1156
z @ event.ts:1167
fire @ event.ts:1191
addNotification @ notifications.ts:228
notify @ notificationService.ts:253
(anonymous) @ mainThreadMessageService.ts:86
f @ mainThreadMessageService.ts:51
$showMessage @ mainThreadMessageService.ts:45
S @ rpcProtocol.ts:458
Q @ rpcProtocol.ts:443
M @ rpcProtocol.ts:373
L @ rpcProtocol.ts:299
(anonymous) @ rpcProtocol.ts:161
y @ event.ts:1156
fire @ event.ts:1187
fire @ ipc.net.ts:650
q.onmessage @ localProcessExtensionHost.ts:376
console.ts:137 [Extension Host] [WakaTime][DEBUG] Sending heartbeat: /Users/pbb/.wakatime/wakatime-cli-darwin-arm64 --entity /Users/pbb/Downloads/Test/main.tex --plugin "\"vscode/1.88.1 vscode-wakatime/24.5.0\"" --lineno 24 --cursorpos 14 --lines-in-file 30 --alternate-project Test --project-folder /Users/pbb/Downloads/Test
console.ts:137 [Extension Host] [WakaTime][DEBUG] Fetching coding activity for Today from api: /Users/pbb/.wakatime/wakatime-cli-darwin-arm64 --today --output json --plugin "\"vscode/1.88.1 vscode-wakatime/24.5.0\""
console.ts:137 [Extension Host] --> Run Command: inkscape-figures edit "${fileDirname}/Figures/"
console.ts:137 [Extension Host] --> Run Command: inkscape-figures edit "${fileDirname}/Figures/"

</details>

**Comment by iamhyc** [comment]
Ok, I get the point. We should blame the overleaf server.

When overwrite existing file on overleaf server, it will trigger "delete-then-update" action instead of only update.

----
The denoised log are attached for your interest.
<details>

console.ts:137 [Extension Host] 5/17/2024, 1:50:13 PM [push] update "/Figures/test.svg" -1 --> 1972868926
console.ts:137 [Extension Host] 5/17/2024, 1:50:13 PM [push] update "/Figures/test.pdf" -1 --> 1924242771
console.ts:137 [Extension Host] 5/17/2024, 1:50:13 PM [push] update "/Figures/test.pdf_tex" -1 --> -2092866401

console.ts:137 [Extension Host] --> Run Command: inkscape-figures edit "${fileDirname}/Figures/"

console.ts:137 [Extension Host] 5/17/2024, 1:50:22 PM [push] update "/Figures/test.svg" 1972868926 --> 1620541927
console.ts:137 [Extension Host] 5/17/2024, 1:50:23 PM [push] update "/Figures/test.pdf" 1924242771 --> -922936231
console.ts:137 [Extension Host] 5/17/2024, 1:50:23 PM [push] update "/Figures/test.pdf_tex" -2092866401 --> 1703342341

console.ts:137 [Extension Host] 5/17/2024, 1:50:23 PM [pull] delete "/Figures/test.pdf_tex" 1703342341 --> -1
console.ts:137 [Extension Host] 5/17/2024, 1:50:23 PM [pull] update "/Figures/test.pdf_tex" -1 --> 1703342341
console.ts:137 [Extension Host] 5/17/2024, 1:50:23 PM [pull] update "/Figures/test.pdf_tex" 1703342341 --> 0

console.ts:137 [Extension Host] 5/17/2024, 1:50:23 PM [pull] delete "/Figures/test.svg" 1620541927 --> -1
console.ts:137 [Extension Host] 5/17/2024, 1:50:23 PM [pull] update "/Figures/test.svg" -1 --> 0
console.ts:137 [Extension Host] 5/17/2024, 1:50:23 PM [pull] update "/Figures/test.svg"

console.ts:137 [Extension Host] 5/17/2024, 1:50:23 PM [push] delete "/Figures/test.svg"
console.ts:137 [Extension Host] 5/17/2024, 1:50:23 PM [push] delete "/Figures/test.pdf_tex"

console.ts:137 [Extension Host] 5/17/2024, 1:50:24 PM [pull] delete "/Figures/test.pdf" -922936231 --> -1
console.ts:137 [Extension Host] 5/17/2024, 1:50:24 PM [pull] update "/Figures/test.pdf" -1 --> -922936231

</details>

**Comment by sleepymalc** [comment]
Hmm, in this case, is this fixable on the extension side? I would imagine if sync file updates with some delay maybe the interference can be avoided? I don't know just a guess.

**Comment by iamhyc** [comment]
> Hmm, in this case, is this fixable on the extension side? I would imagine if sync file updates with some delay maybe the interference can be avoided? I don't know just a guess.

Yes, it can be fixed and I just find some bugs in the previous implementation. I need some time to fix it.

**Comment by iamhyc** [comment]
Hi @sleepymalc , it now at least working on my side again, though with some error message.

Please try with the temporary extension here:
https://github.com/iamhyc/Overleaf-Workshop/actions/runs/9148809555

**Comment by sleepymalc** [comment]
This is my test demo:

https://github.com/iamhyc/Overleaf-Workshop/assets/60427058/92ad28eb-4235-450b-adc8-638e218f36fd

After initial pasting it fails already. Not sure whether it's because it's `xxx.pdf` (but previously at least the first pasting is fine even if there's a `xxx.pdf`).

Here's the log:

<details>

console.ts:137 [Extension Host] 5/20/2024, 1:14:30 AM [push] update "/Figures/test.pdf_tex" -1 --> 1703342341
console.ts:137 [Extension Host] 5/20/2024, 1:14:30 AM [push] update "/Figures/test.pdf_tex"
console.ts:137 [Extension Host] 5/20/2024, 1:14:30 AM [push] update "/Figures/test.pdf" -1 --> -922936231
console.ts:137 [Extension Host] 5/20/2024, 1:14:30 AM [push] update "/Figures/test.pdf"
console.ts:137 [Extension Host] 5/20/2024, 1:14:30 AM [push] update "/Figures/test.svg" -1 --> 1620541927
console.ts:137 [Extension Host] 5/20/2024, 1:14:30 AM [push] update "/Figures/test.svg"
console.ts:137 [Extension Host] 5/20/2024, 1:14:32 AM [push] update "/Figures/test.pdf" -922936231 --> 573999856
console.ts:137 [Extension Host] 5/20/2024, 1:14:32 AM [push] update "/Figures/test.pdf"
console.ts:137 [Extension Host] 5/20/2024, 1:14:34 AM [pull] delete "/Figures/test.pdf" 573999856 --> -1
console.ts:137 [Extension Host] 5/20/2024, 1:14:34 AM [pull] delete "/Figures/test.pdf"


</details>

**Comment by iamhyc** [comment]
well, I believe there is something wrong with "vfs" (which connects to overleaf via websocket), but not local replica.

You can see there is no "delete action" push to server, but "vfs" detects the file deletion and try to sync to local replica.

I will check it later, but I think maybe we can merge the fixes into mainline for now, if there is nothing wrong except for the weird pdf file.

**Comment by sleepymalc** [comment]
Actually I don't think it's `xxx.pdf`'s fault. I tried other pdf files but cannot recreate this issue: instead, this only happens when my workflow is exporting `xxx.pdf` and `xxx.pdf_tex`. 

The workflow is based on Inkscape. So, I think maybe the easiest way to reproduce this problem is to use Inkscape and do a manual export and see... Not sure how much work will this be on your side.

https://github.com/iamhyc/Overleaf-Workshop/assets/60427058/eec0df02-0392-4b41-b89a-fb946f801c48

For example, I first export manually, which is fine. But when I do this for the second time and overwrite, things went wrong.

**Comment by iamhyc** [comment]
ok, I can try your workflow on my side. Just let me know the script for exporting the pdf file.

**Comment by sleepymalc** [comment]
Hmm let me clarify: the workflow is about using the drawing app called [Inkscape](https://inkscape.org/). I believe that this workflow is too complicated to setup but essentially what it did is when it sees a svg, it opens Inkscape, import the svg into which, and export it to *Portable Document Format (*.pdf)* (as used in the above demo), which creates `xxx.pdf` and `xxx.pdf_tex` that LaTeX can then parse.
I found out that to recreate the problem, it enough to manually export some `*.svg` as *Portable Document Format (*.pdf)*. By doing it twice (and replace the original ones), the problem shows up. So I guess using Inkscape suffices.

**Comment by iamhyc** [comment]
https://github.com/iamhyc/Overleaf-Workshop/actions/runs/9153963106

@sleepymalc This one should work better. I have not done thorough test, let me know if there are any bugs.

**Comment by sleepymalc** [comment]
Yes, I think I still encounter some bugs like not syncing perfectly between local and Overleaf server. But sometimes it works and at least it won't randomly delete my files.

**Comment by iamhyc** [comment]
https://github.com/iamhyc/Overleaf-Workshop/actions/runs/9158121249?pr=138

@sleepymalc Please try this one.

**Comment by iamhyc** [comment]
> It seems like there's no error message showing up, but when I re-export figures, the Overleaf doesn't seem to see the update.

Find a stupid typo. The updated extension is here:
https://github.com/iamhyc/Overleaf-Workshop/actions/runs/9158931477?pr=138

**Comment by sleepymalc** [comment]
Ah great. By a quick test everything seems to work. I'll keep using this extensively and see whether this is stable.
