### ISSUE TITLE
Overleaf Captcha issue

### ISSUE THREAD

**Issue by NNCT2904** [iamhyc/Overleaf-Workshop#14]
# What Happened
Cannot login to host `https://www.overleaf.com/`

# Steps to reproduce
1. Add host `https://www.overleaf.com/`
2. Input Email and Password

# Error Message

400: {"errorReason":"cannot_verify_user_not_robot","message":{"text":"Sorry, we could not verify that you are not a robot. Please check that Google reCAPTCHA is not being blocked by an ad blocker or firewall."}}

<img width="536" alt="Screenshot 2023-09-19 at 4 08 30 pm" src="https://github.com/iamhyc/Overleaf-Workshop/assets/44821915/75089abc-f095-4dea-a23a-c106316c7edb">

**Comment by iamhyc** [comment]
Login to `www.overleaf.com` is not supported.

Though you can login with cookies extracted from browser (the feature will appear in `v0.2.0`), the `overleaf.com` use different `socket.io` version. There is still a lot of work to be done.

**Comment by NNCT2904** [comment]
Awesome work, thanks for informing me, I am looking forward to trying that out!
