### ISSUE TITLE
Better handling of creating new local repo

### ISSUE THREAD

**Issue by sleepymalc** [iamhyc/Overleaf-Workshop#140]
### Disclaimer
> Please make sure all the items below is checked (i.e., prefixed with "- [x]")
- [x] The request feature has not been addressed in the [feature request list](https://github.com/iamhyc/Overleaf-Workshop/issues?q=is%3Aissue+label%3A%22feature+request%22+).
- [x] The design of the feature does not require detailed discussion, or existing discussion with drawn conclusion can be found in [Discussions Area](https://github.com/iamhyc/Overleaf-Workshop/discussions) at: [paste the link here]

### Motivation
> Please give strong enough reason(s) why the feature is demanded.
- To match the default behavior of VS Code when opening folder.

### Feature Description
> A clear and concise description of what you want to happen under what circumstance.
- When not selecting anything when choosing the folder to create the local project, after hitting `Enter`, it should directly confirm rather than pasting the current directory's name. The current way to confirm the desired file path is to click, which is very sub-optimal.

### [Optional] Additional context
> Please strike out any inappropriate items below. If you are not aware of the difference, please ignore this section.
- **Applicable Overleaf Edition**: Official / Community / Enterprise (Server Pro)
- **Applicable Extension Range**: Desktop Extension / Web Extension
The following is a demo when you try to open a project locally while there's no existing local copy. It'll first prompt you whether you want to create it locally, and the demo shows what happens after you click `Yes` to the above prompt:

https://github.com/iamhyc/Overleaf-Workshop/assets/60427058/368b12f7-e59e-4a6c-8815-c66183d77206

After I reach the desired path (in this case, `xxx/Downloads`) and hits `Enter`, I expect it'll hit confirm for me rather than pasting the current directory's name again.

**Comment by iamhyc** [comment]
Thanks for the feedback. I will fix the bug later ... after solving #134 of course.

**Comment by sleepymalc** [comment]
Sure. This is a pretty minor bug compared to #134 and it has a workaround at least.

**Comment by sleepymalc** [comment]
I just tested the feature again. I think the only remaining complaint is that it should start by user's directory not the root (in macOS, I start with `.`, but my personal root is`./Users/pbb/`). Maybe this is a easy fix?

**Comment by iamhyc** [comment]
> I just tested the feature again. I think the only remaining complaint is that it should start by user's directory not the root (in macOS, I start with `.`, but my personal root is`./Users/pbb/`). Maybe this is a easy fix?

I am worrying about the os-related separator. I have tested it working on Windows, please help me test if it works on unix-like os. Thank you!

https://github.com/iamhyc/Overleaf-Workshop/actions/runs/9159385501

**Comment by sleepymalc** [comment]
Yes, this works. Thanks!
