### ISSUE TITLE
[Feature Request] Paste image support 

### ISSUE THREAD

**Issue by Lazer2077** [iamhyc/Overleaf-Workshop#142]
Thanks for your contribution to the LaTex community！

### Motivation

In normal LaTex edit in vscode, copy and paste image can be implement with some extension like "paste image" or "Latex Utilities". In my guess they paste the image from clipboard into the current folder.  However, in this extension paste image may not work because the it can't not upload the image to the overleaf. 

### [Optional] Additional context
LaTex Utilities:  https://github.com/tecosaur/LaTeX-Utilities
Paste Image: https://github.com/mushanshitiancai/vscode-paste-image

**Comment by iamhyc** [comment]
Hi, if you would like to enable more extensions, please refer to "open project locally"
https://github.com/iamhyc/Overleaf-Workshop/blob/master/docs/wiki.md#open-project-locally

**Comment by Lazer2077** [comment]
Thanks for your response, but I still found that it is not work on "open project locally..." with latest version of extension

**Comment by iamhyc** [comment]
> Thanks for your response, but I still found that it is not work on "open project locally..." with latest version of extension

When you open project locally, you basically manipulate with a local folder open in vscode. I have no idea why it does not work.

**Comment by Lazer2077** [comment]
I try to follow the instruction in the link, which is "Right click on the project and select Open Project Locally...", dialog will no pop out and app doesn't respond in any other way

**Comment by iamhyc** [comment]
> I try to follow the instruction in the link, which is "Right click on the project and select Open Project Locally...", dialog will no pop out and app doesn't respond in any other way

I see. I thought you have set up the local replica.

Please check if you can see the "people" icon after clicking "open project locally ...".

The extension will firstly connect to the server and then pop up the prompt.

![](https://github.com/iamhyc/Overleaf-Workshop/assets/9068301/a387f8a0-de04-47c7-9621-669a9cd22020)

**Comment by Lazer2077** [comment]
Ok, it work after I change to another computer, thanks you!
