### ISSUE TITLE
How to upload an image in my computer to an Overleaf project on the VSCode page

### ISSUE THREAD

**Issue by velonica0** [iamhyc/Overleaf-Workshop#145]
### Motivation
> Please give strong enough reason(s) why the feature is demanded.
-Now I can't find a way to upload my images on the vscode page
- Is it possible to compile on vscode only by uploading images on the overleaf web page?

### Feature Description
> A clear and concise description of what you want to happen under what circumstance.
- I'd like to be able to upload images like Overleaf on the vscode page
-

**Comment by iamhyc** [comment]
Simply drag and drop the file into vscode explorer on sidebar.

**Comment by velonica0** [comment]
> Simply drag and drop the file into vscode explorer on sidebar.

thanks
