### ISSUE TITLE
Auto-completion for references in .bib files when typing \cite{...} doesn't work with biblatex

### ISSUE THREAD

**Issue by elyurn** [iamhyc/Overleaf-Workshop#146]
Following a previous issue, auto-completion of references for citations was added: https://github.com/iamhyc/Overleaf-Workshop/issues/61
It works well for .bib files with a Bibtex format, but **it doesn't seem to work for .bib files formatted for BibLatex** bibliography.

### Environment
 - **Overleaf Workshop Extension version**: v0.12.2
 - **VS Code version**: 1.89.1
 - **Overleaf Edition**: Enterprise (Server Pro)

**Comment by iamhyc** [comment]
@QianrenLi Please have a look at it when you are free.

**Comment by QianrenLi** [comment]
Hi, @elyurn. A quick fix has been proposed. If you have any spare, please give it a try to see whether this fix solves your problem.

(Fix: https://github.com/iamhyc/Overleaf-Workshop/actions/runs/9263067184/artifacts/1542608312)

**Comment by elyurn** [comment]
Thank you @QianrenLi! It works well. 👍
