### ISSUE TITLE
[Feature Request] Add Setting to Exclude Specific Files/Folders from Sync

### ISSUE THREAD

**Issue by Fisher-Wang** [iamhyc/Overleaf-Workshop#149]
### Motivation
- I want to have local settings specific to the workspace, like font type, color theme, ...
- When I use this extension to collaborate with my partners who use Overleaf from browsers, the '.vscode' folder appears in their file list and is unnecessary for them
- When I use it with partners who also use this extension, we may also want to have local settings specific to the workspace. These personalized settings shouldn't be synchronized.

### Feature Description
- Add a setting item, of string type, where the relative file path matching this string will not be synced
  For example
  ```json
  {
    "overleaf-workshop.excludeFromSync": ".vscode/*"
  }
  ```

**Comment by iamhyc** [comment]
Hi, I think you should avoid setup workspace-specific settings when manipulate with the overleaf virtual filesystem. You can try to "open project locally" instead (the guidance is [here](https://github.com/iamhyc/Overleaf-Workshop/blob/master/docs/wiki.md#open-project-locally)).

On the other hand, even "exclude from sync" is possible, it will also be user/machine-specific settings, but not for workspace. The workspace-specific settings are always stored at the root of the workspace folder.
