### ISSUE TITLE
“No Local Replica Found” Notification After Inactivity

### ISSUE THREAD

**Issue by chenhengzh** [iamhyc/Overleaf-Workshop#153]
### Describe the bug
If I stop activities for a period, the cloud icon at the bottom will disappear, and my local replica cannot sync with Overleaf. At this point, when I hit "Open Project Locally..." again, it shows "No Local Replica Found."

### Expected behavior
I wish that my local replica can keep sync I cancel it

### How To Reproduce

Close the local replica for a period

### Environment
 - **Overleaf Workshop Extension version**: [e.g., 0.7.0]
 - **VS Code version**: [e.g. 1.85.0]
 - **Overleaf Edition**: Official / Community / Enterprise (Server Pro)

**Comment by iamhyc** [comment]
Hi @chenhengzh , I will check it later tomorrow.

The local replica (or the cloud icon on status bar) would be automatically deleted, when there is any error happened in the sync.

I also need to know how you "stop activities for a period". Please try to give detailed description so I can reproduce the situation on my side.

**Comment by chenhengzh** [comment]
Thank you for your rapid response! I just discovered that the cloud icon disappears if I don’t perform any operations for a while (possibly due to sync errors during this period). And I have to create a new local replica again and wait for at least several minutes. This is very troublesome. I’m not sure if this is a bug or due to my improper usage.

**Comment by iamhyc** [comment]
@chenhengzh Hi, I found the automatic removal only happen at the initial setup of local replica. That is to say, the "idle for a while " will not cause the removal of local replica.

For now, I simply disable the "automatic removal" and only show error message instead. The fix is also included in PR #155 .
