### ISSUE TITLE
I cannot create another local replica if one already exists.

### ISSUE THREAD

**Issue by chenhengzh** [iamhyc/Overleaf-Workshop#154]
### Describe the bug

Sometimes I have created a local replica with wrong path. And I delete the dictionary. But when I want to create a local replica again, it just lets me "select a local replica below" and I cannot create a new local replica.

![image](https://github.com/iamhyc/Overleaf-Workshop/assets/74190205/30bc19dc-2291-48a8-8c0e-ee8fac5b7940)

### Expected behavior

I wish I can create new local replica rather than just select one from given list.

### How To Reproduce
Just create a local replica and re-hit the "open project locally"
### Environment
 - **Overleaf Workshop Extension version**: [e.g., 0.7.0]
 - **VS Code version**: [e.g. 1.85.0]
 - **Overleaf Edition**: Official / Community / Enterprise (Server Pro)

**Comment by iamhyc** [comment]
You need to delete it in the scm settings. Please follow the guidance here:
https://github.com/iamhyc/Overleaf-Workshop/blob/master/docs/wiki.md#local-replica-source-control

**Comment by chenhengzh** [comment]
Yes, but I have to wait until the wrong local replica is fully created (which takes at least several minutes), open the project, and do a lot of operations. This process is quite troublesome.
If I could create, choose, or stop the local replica directly from the Overleaf workshop hosts, it would be much more convenient.

**Comment by iamhyc** [comment]
> Yes, but I have to wait until the wrong local replica is fully created (which takes at least several minutes), open the project, and do a lot of operations. This process is quite troublesome. If I could create, choose, or stop the local replica directly from the Overleaf workshop hosts, it would be much more convenient.

I see. You have a large project so it takes a lot of time to sync at the start.

I think I can add a progress bar when applying the bulky update, and you can cancel the sync in the middle.

**Comment by chenhengzh** [comment]
Thanks! It will be a wonderful function. Looking forward to the update.

**Comment by iamhyc** [comment]
Hi, please try this temporarily packed extension:
https://github.com/iamhyc/Overleaf-Workshop/actions/runs/9524443666

It will notify you the bulky sync progress at the start when create/open a local replica. You can also try to cancel the sync process.

Now I do not handle the after effect of interrupt of bulky sync. The user who click the cancel button should be aware of the risk.

**Comment by chenhengzh** [comment]
Thank you for your update. It’s much more convenient than before. However, if possible, I would like to have an option to disable/remove old local replicas or create a new local replica directly after clicking “Open Project Locally…”. This option would allow us to change the path of a local replica easily.

Currently, if a local replica has been created, I can only open it without any other options, as shown in the figure below. If I want to change the path of the local replica, I have to open the existing local replica, wait for the connection, disable it, go back to the Overleaf workspace, and then open a new one. This process is quite troublesome.

<img width="1317" alt="image" src="https://github.com/iamhyc/Overleaf-Workshop/assets/74190205/8b254719-bb90-4ed2-aa84-537a99582cb3">

**Comment by iamhyc** [comment]
> Thank you for your update. It’s much more convenient than before. However, if possible, I would like to have an option to disable/remove old local replicas or create a new local replica directly after clicking “Open Project Locally…”. This option would allow us to change the path of a local replica easily.
> 
> Currently, if a local replica has been created, I can only open it without any other options, as shown in the figure below. If I want to change the path of the local replica, I have to open the existing local replica, wait for the connection, disable it, go back to the Overleaf workspace, and then open a new one. This process is quite troublesome.

Sounds reasonable, I will check it today.

**Comment by iamhyc** [comment]
> Thank you for your update. It’s much more convenient than before. However, if possible, I would like to have an option to disable/remove old local replicas or create a new local replica directly after clicking “Open Project Locally…”. This option would allow us to change the path of a local replica easily.
> 
> Currently, if a local replica has been created, I can only open it without any other options, as shown in the figure below. If I want to change the path of the local replica, I have to open the existing local replica, wait for the connection, disable it, go back to the Overleaf workspace, and then open a new one. This process is quite troublesome.

Sorry for the late reply. The feature has been implemented in PR #155 . It will be available in the next release.

**Comment by chenhengzh** [comment]
Thank you for reply. Looking forward to the next release
