### ISSUE TITLE
Using undo when multiple users are editing

### ISSUE THREAD

**Issue by pramodhrachuri** [iamhyc/Overleaf-Workshop#158]
### Describe the bug
> A clear and concise description of what the bug is.
When two users edit the same document, and one presses undo, the other user's edits can also get removed.

### Expected behavior
> A clear and concise description of what you expected to happen.
Undo should remove the edit of the user who presses the undo button.

### How To Reproduce
> Detailed steps to reproduce the behavior.
User 1: Make an edit
User 2: Make another edit somewhere else
User 1: press undo
Effect: User 2's edits gets removed

### Environment
 - **Overleaf Workshop Extension version**: v0.12.3
 - **VS Code version**: 1.90.2
 - **Overleaf Edition**: Official

### [Optional] Developer Logs
> If applicable, please paste the logs inside the details section below.
> Please find the logs via: Title bar **"Help"** > **"Toggle Developer Tools"** > **"Console"**.

**Comment by iamhyc** [comment]
If I get you correctly, "ctrl+z" on user 1's side would undo user2' edits.

I see there is nothing wrong. You are both editing the same document and the undo could not be separately done.
