### ISSUE TITLE
Draw option picks objects

### ISSUE THREAD

**Issue by PRigas96** [iamhyc/Overleaf-Workshop#161]
### Describe the bug
I use _draw_ on pdf for some notes / when talking about the pdf w/ colleagues. When I try to draw on top the bounding box of a latter draw, i.e. do a circle and draw inside it, I instead pick the object, which is the circle.

### Expected behavior
The ability to pick objects should be available only when _draw_ is off

### How To Reproduce
1) press _draw_
2) draw something (circle, some smudges)
3) draw upon it

### Environment
 - **Overleaf Workshop Extension version**: [e.g., 0.7.0]
 - **VS Code version**: [e.g. 1.85.0]
 - **Overleaf Edition**: Official / Community / Enterprise (Server Pro)

**Comment by iamhyc** [comment]
I think this is the default behavior of "pdf.js". You can try with the official demo here:

https://mozilla.github.io/pdf.js/web/viewer.html

**Comment by PRigas96** [comment]
yeah you're right; I'll close the issue
