### ISSUE TITLE
[Feature Request] Keyboard Shortcut for surrounding text with \textbf etc

### ISSUE THREAD

**Issue by pramodhrachuri** [iamhyc/Overleaf-Workshop#162]
### Disclaimer
> Please make sure all the items below is checked (i.e., prefixed with "- [x]")
- [x] The request feature has not been addressed in the [feature request list](https://github.com/iamhyc/Overleaf-Workshop/issues?q=is%3Aissue+label%3A%22feature+request%22+).
- [x] The design of the feature does not require detailed discussion, or existing discussion with drawn conclusion can be found in [Discussions Area](https://github.com/iamhyc/Overleaf-Workshop/discussions) at: [paste the link here]

### Motivation
> Please give strong enough reason(s) why the feature is demanded.
- We are used to basic text formatting like bold, italic, underline because of MS Word, Libreoffice and Google Docs
- This is a small quality-of-life improvement for basic text formatting

### Feature Description
> A clear and concise description of what you want to happen under what circumstance.
- While writing papers, we tend to use Bold, Italics and Underlines. Adding a keyboard shortcut to automatically surround text with \textbf, \textit, \uline around any selected text will be handy
- In the setting menu, the user should be able to define whatever macro they want to use and the keyboard shortcut for it.
Example list-

| Name (optional)     | Macro   | Shortcut |
|---------------------|---------|----------|
| Bold                | textbf  | Ctrl+B   |
| Italic              | textit  | Ctrl+I   |
| Red colored font    | red     | Ctrl+R   |

- The users are responsible to define the macros or import relavent package in the latext code

### [Optional] Additional context
> Please strike out any inappropriate items below. If you are not aware of the difference, please ignore this section.
- ~~**Applicable Overleaf Edition**: Official / Community / Enterprise (Server Pro)~~
- ~~**Applicable Extension Range**: Desktop Extension / Web Extension~~

**Comment by iamhyc** [comment]
The related discussion is here: https://github.com/iamhyc/Overleaf-Workshop/discussions/129

For now, I still think it is not necessary to have those extra shortcuts.
