### ISSUE TITLE
Reference autocompletion doesn't work with "\textcite"

### ISSUE THREAD

**Issue by Sh4wnChen** [iamhyc/Overleaf-Workshop#165]
### Describe the bug
> The reference autocompletion works fine with `\cite` but doesn't work with `\textcite` or `\citet`
> For now I can only use `\cite` first to find the reference and change the command to others.

### Environment
 - **Overleaf Workshop Extension version**: [v0.13.0]
 - **VS Code version**: [1.91.0]
 - **Overleaf Edition**: Official

**Comment by iamhyc** [comment]
@QianrenLi Please have a look at it when you are free.

**Comment by QianrenLi** [comment]
Hi @Sh4wnChen, please give this patch https://github.com/iamhyc/Overleaf-Workshop/actions/runs/9850231285/artifacts/1680326921 a try to see if this solve your problem.

**Comment by Sh4wnChen** [comment]
@QianrenLi 
Thank you for your help! It works perfectly now.
