### ISSUE TITLE
Unable to turn linting off

### ISSUE THREAD

**Issue by devinat1** [iamhyc/Overleaf-Workshop#167]
### Describe the bug
I am getting blue squiggly lines (linting markers) under the \cite options and other text. I am unable to disable these markers in any way when using overleaf workshop.
![Screenshot from 2024-07-12 14-32-26](https://github.com/user-attachments/assets/44e9da7e-5fac-42f8-bdc7-da719b301aaf)

### Expected behavior
Provide an option to completely disable linting and spell checking.

### How To Reproduce
Open any latex file with overleaf workshop and edit a document (such as by citing a bib file).

### Environment
 - **Overleaf Workshop Extension version**: 0.13.0
 - **VS Code version**: 1.91.0
 - **Overleaf Edition**: Official

**Comment by iamhyc** [comment]
If you mean to turn off the spell check, you can check it on the status bar.

![image](https://github.com/user-attachments/assets/d033c32b-727e-4f2c-b1ff-a6b6fe36885e)
