### ISSUE TITLE
[Feature Request] Add support for MNRAS \citep and \citet commands

### ISSUE THREAD

**Issue by JotaRata** [iamhyc/Overleaf-Workshop#168]
### Disclaimer
> Please make sure all the items below is checked (i.e., prefixed with "- [x]")
- [x] The request feature has not been addressed in the [feature request list](https://github.com/iamhyc/Overleaf-Workshop/issues?q=is%3Aissue+label%3A%22feature+request%22+).
- [x] The design of the feature does not require detailed discussion, or existing discussion with drawn conclusion can be found in [Discussions Area](https://github.com/iamhyc/Overleaf-Workshop/discussions) at: [paste the link here]

### Motivation
> Please give strong enough reason(s) why the feature is demanded.
- The Monthly Notices of the Royal Astronomical Society (MNRAS) and the Astrophysical Jorunal both use their own document classes with special commands that make citing easier, two of them are \citep and \citet that allows to cite in parentheses and textually respectively.
- 

### Feature Description
> A clear and concise description of what you want to happen under what circumstance.
- Overleaf worshop should support these two commands the same way it has support for the \cite command, that is mainly allow for auto-completions for the references.
- Alternatively it could also support custom commands that behave the same? maybe expose a setting to have different "aliases" for \cite and other commonly used commands

**Comment by QianrenLi** [comment]
Please refer to #165 to see if this [patch](https://github.com/iamhyc/Overleaf-Workshop/actions/runs/9850231285/artifacts/1680326921) solves your problem. If everything goes right, the new patch will be published soon.

**Comment by JotaRata** [comment]
It works perfectly, thanks!
