### ISSUE TITLE
[Feature Request] Add the compile mode (normal & fast)

### ISSUE THREAD

**Issue by leiqianstat** [iamhyc/Overleaf-Workshop#173]
### Disclaimer
> Please make sure all the items below is checked (i.e., prefixed with "- [x]")
- [x] The request feature has not been addressed in the [feature request list](https://github.com/iamhyc/Overleaf-Workshop/issues?q=is%3Aissue+label%3A%22feature+request%22+).
- [x] The design of the feature does not require detailed discussion, or existing discussion with drawn conclusion can be found in [Discussions Area](https://github.com/iamhyc/Overleaf-Workshop/discussions) at: [paste the link here]

### Motivation
> Please give strong enough reason(s) why the feature is demanded.
- When my paper does not contain any pictures, I prefer to compile by fast compile mode. It can be faster.

### Feature Description
> A clear and concise description of what you want to happen under what circumstance.
-  Add the compile mode.
<img width="198" alt="de447679af66a4dec555873fddb4c20" src="https://github.com/user-attachments/assets/bfd370a1-8fd9-46f1-a4af-943c345bd073">

### [Optional] Additional context
> Please strike out any inappropriate items below. If you are not aware of the difference, please ignore this section.
- **Applicable Overleaf Edition**: Official / Community / Enterprise (Server Pro)
- **Applicable Extension Range**: Desktop Extension / Web Extension

**Comment by iamhyc** [comment]
@leiqianstat  Thanks for the suggestion! I wonder if people also care about the other two options, "syntax checks" and "compile error handling". Now I just use the default options in compiling. Let me know what you think!

**Comment by leiqianstat** [comment]
> @leiqianstat Thanks for the suggestion! I wonder if people also care about the other two options, "syntax checks" and "compile error handling". Now I just use the default options in compiling. Let me know what you think!

In fact, I always adjust the compile mode and use the default setting in the other two options.

**Comment by iamhyc** [comment]
![](https://github.com/user-attachments/assets/8f8df792-409c-4a1a-9b8e-ae7d9d1fe875)

Please try the temporary extension here: https://github.com/iamhyc/Overleaf-Workshop/actions/runs/10346416708

The feature will be formally included in the next release.

**Comment by leiqianstat** [comment]
> ![](https://private-user-images.githubusercontent.com/9068301/356942868-8f8df792-409c-4a1a-9b8e-ae7d9d1fe875.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM0NDEyOTcsIm5iZiI6MTcyMzQ0MDk5NywicGF0aCI6Ii85MDY4MzAxLzM1Njk0Mjg2OC04ZjhkZjc5Mi00MDljLTRhMWEtOWI4ZS1hZTdkOWQxZmU4NzUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MTJUMDUzNjM3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MWFiNTcwZTEyYzc0NTBkMjFiZjg1YjVkMTExNzBiYjhhZTZkZmM5NDU4NDA1MTExZGU0NzI4YmIwNGFkMzcyOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.frVZraerj1kv_NQIHug154o74aGckd_goya16Fxceho)
> 
> Please try the temporary extension here: https://github.com/iamhyc/Overleaf-Workshop/actions/runs/10346416708
> 
> The feature will be formally included in the next release.

This solved my problem, thank you！
