### ISSUE TITLE
Updated files are overwritten with an older version after starting VSCode

### ISSUE THREAD

**Issue by bitosky** [iamhyc/Overleaf-Workshop#175]
### Describe the bug
I did some update outside VSCode. After that, I started VSCode, but overleaf workshop download the old version of these files replaces the new versions.  

### Expected behavior
The overleaf workshop should compare the file versions, and upload the new version files to overleaf.

### How To Reproduce
Just like the above descriptoins.

### Environment
 - **Overleaf Workshop Extension version**: 0.13.2
 - **VS Code version**: 1.88.1
 - **Overleaf Edition**: Official

### [Optional] Developer Logs
> If applicable, please paste the logs inside the details section below.
> Please find the logs via: Title bar **"Help"** > **"Toggle Developer Tools"** > **"Console"**.

<details>
  ...
</details>

**Comment by iamhyc** [comment]
Since there is no more feedback, I will mark this issue as a "question" and close it now.
