### ISSUE TITLE
cannot compile project

### ISSUE THREAD

**Issue by YLChen-007** [iamhyc/Overleaf-Workshop#181]
### Describe the bug
When click the "compile project" Button, no action responses.

![image](https://github.com/user-attachments/assets/96d7077d-e09f-40b6-9f53-d1902283462a)

**Comment by iamhyc** [comment]
Please use the [bug report](https://github.com/iamhyc/Overleaf-Workshop/issues/new?assignees=&labels=bug&projects=&template=bug_report.md&title=) template and attach the developer logs. Thank you.

**Comment by YLChen-007** [comment]
where is the "developer logs"?

**Comment by iamhyc** [comment]
![图片](https://github.com/user-attachments/assets/28935c3a-2b5a-4d07-82e4-6a6653e2a0b5)

**Comment by YLChen-007** [comment]
when i click the "compile project" button. No log out put.
![image](https://github.com/user-attachments/assets/05cc4e2d-766c-4bed-84d1-2886dfe6f656)

**Comment by iamhyc** [comment]
If so, the compile just stucked there. Please check your network connection.

https://github.com/iamhyc/Overleaf-Workshop/blob/master/docs/wiki.md#q3-why-the-extension-loses-connection-to-the-server-frequently-or-loading-indefinitely

**Comment by YLChen-007** [comment]
I have checked no proxy used for overleaf-workshop. 
![image](https://github.com/user-attachments/assets/b1121d87-5673-4004-ae48-3bb92740a6ec)
I cannot entry Invisiable mode . stucking !
![image](https://github.com/user-attachments/assets/56130c18-54d7-4684-8920-331cea0848be)

**Comment by YLChen-007** [comment]
Thanks your attention. I solved this problem.
