### ISSUE TITLE
Syncing temporarily latexindent files

### ISSUE THREAD

**Issue by sleepymalc** [iamhyc/Overleaf-Workshop#182]
### Describe the bug
> A clear and concise description of what the bug is.

When working with the local environment and with `latexindent`, when formatting, a tmp file will be created and then deleted. This causes some mess when managing the editing history on Overleaf.

<img width="317" alt="image" src="https://github.com/user-attachments/assets/f0fede94-53c0-41ef-b37e-5fc0b6db3a70">

### Expected behavior
> A clear and concise description of what you expected to happen.

Exclude this type of tmp file from syncing.

### How To Reproduce
> Detailed steps to reproduce the behavior.

Using `latexindent` should reproduce the issue.

### Environment
 - **Overleaf Workshop Extension version**: 0.13.2
 - **VS Code version**: 1.92.2
 - **Overleaf Edition**: Official

**Comment by iamhyc** [comment]
Please refer to the wiki and update the sync ignore pattern:
https://github.com/iamhyc/Overleaf-Workshop/blob/master/docs/wiki.md#local-replica-source-control

As `__*` is not a common prefix to exclude, I may not update it in the default list.

**Comment by sleepymalc** [comment]
Thanks for the direction, works well with `**/__latexindent_temp_*.tex`.
