### ISSUE TITLE
Connection Lost

### ISSUE THREAD

**Issue by aayushdesai** [iamhyc/Overleaf-Workshop#186]
I am trying to log into an Overleaf Community server hosted by my institute. I can login both via password and via cookies. I know it has logged in, because I can see the listed projects. But I cannot open any of them as VS Code keeps reporting connection lost. 

I see that this issue was raised late last year and [resolved](https://github.com/iamhyc/Overleaf-Workshop/issues/42). But I seem to have hit the same snag. 

The exact error pop up is:

Unable to read file 'overleaf-workshop://overleaf.xxx/Project?user=66f414971c496299c1f6a6ccasdfa&project=66f414c51c496299c1f6a6fcadsf' (Error: Connection lost)

What should I do?

**Comment by iamhyc** [comment]
Hi @aayushdesai , the mentioned issue may not be related.

Please firstly check if the full URL entered of the hosted server is correct:
- Is it `http` or strictly `https` website? If you are not sure, please try both the cases.
- Is the full access name `www.overleaf.xxx` or not? (in such case `www` could not be ignored)

**Comment by aayushdesai** [comment]
Hello, I tried http and https, and got the same problem. 

The full access name is https://overleaf.servername.

**Comment by iamhyc** [comment]
> Hello, I tried http and https, and got the same problem.
> 
> The full access name is https://overleaf.servername.

@aayushdesai  Hi, the "connection lost" is the failure of `socket.io` (websocket) connection, and the extension should work correctly with recent commercial and community version. I suggest you check the URL again and check the network proxy following the guidance [here](https://github.com/iamhyc/Overleaf-Workshop/blob/master/docs/wiki.md#q3-why-the-extension-loses-connection-to-the-server-frequently-or-loading-indefinitely). If you find "connect lost" happened after waiting some time, it is more likely a network issue.

If possible, please let us know which version of `socket.io` the server used. You can open the project in webpage, and check the full URL via the developer console as follows (the hostname is not necessary and you can occlude it)

![图片](https://github.com/user-attachments/assets/bcc98bbe-51ce-4be5-a9fa-a09411b0b1da)

**Comment by aayushdesai** [comment]
@iamhyc, thanks. Here is the version of socket.io the server is using:
![Screenshot 2024-09-30 at 10 54 15 AM](https://github.com/user-attachments/assets/bcd49ff1-d12c-4e4b-a8eb-250c03fe9665)

Moreover as I mentioned, the server is reachable, as I am able to see my projects. The disconnection only arises when I try to open any of my projects. I tried to enable/disable network proxy, but still face the same issue. I am a bit skeptical about using invisible mode as I would have to manually commit my changes, which sort of beats the point.
But if there seems to be no other solution, I might give it a go as well.

Thanks

**Comment by iamhyc** [comment]
> @iamhyc, thanks. Here is the version of socket.io the server is using: 
> 
> Moreover as I mentioned, the server is reachable, as I am able to see my projects. The disconnection only arises when I try to open any of my projects. I tried to enable/disable network proxy, but still face the same issue. I am a bit skeptical about using invisible mode as I would have to manually commit my changes, which sort of beats the point. But if there seems to be no other solution, I might give it a go as well.
> 
> Thanks

Thanks for the feedback. However, as the address `/socket.io/1/...` implied, the socketio connection process should be handled correctly in our code.

I still doubt the domain name is wrong. Can you show us more information of the socketio connection address above? E.g. is it 
`https://www.xxx.com/...`, `http://xxx.com/...`, `https://xxx.com/yyy/...`, or something else. It would be helpful.
Then, please remove the previous server in the extension list, and re-create with the correct URL once again.

Besides, please also try to attach the developer logs of "Overleaf-Workshop" extension in VS Code when open the project.
Please find it via Title bar **"Help"** > **"Toggle Developer Tools"** > **"Console"**.
The socketio connection logs will be look like below for a success connection.
![](https://github.com/user-attachments/assets/396ef5c6-3cd0-4765-a3ac-a4ea76dc0707)

**Comment by aayushdesai** [comment]
![Screenshot 2024-09-30 at 11 27 20 AM](https://github.com/user-attachments/assets/97d316a7-9016-4613-8774-f8f5a9be6bdf)
![Screenshot 2024-09-30 at 11 31 03 AM](https://github.com/user-attachments/assets/8f4213d5-e24a-4361-bca7-371f18a063b4)
PFA the requested logs

**Comment by iamhyc** [comment]
So the connection lost is due to 404, quite weird. The web address used for socketio must be wrong.

**Comment by aayushdesai** [comment]
So is there anything I can do to address that?

**Comment by iamhyc** [comment]
> So is there anything I can do to address that?

I got no idea. For now, I can create a debug version for you, which will print out the full URL used by `socketio` in developer console.
You can download the temporary extension here: https://github.com/iamhyc/Overleaf-Workshop/actions/runs/11120227744?pr=192

If you find the printed "Internal Socket URL" is exactly what you see in the browser, then it should be the network problem of VS Code, for some reason.

![](https://github.com/user-attachments/assets/2f6afe0e-1c8a-4aae-8282-3a8313f52365)
