### ISSUE TITLE
[Feature Request] Citation intellisense with better matching for middle words

### ISSUE THREAD

**Issue by wzunknown** [iamhyc/Overleaf-Workshop#190]
### Disclaimer
> Please make sure all the items below is checked (i.e., prefixed with "- [x]")
- [x] The request feature has not been addressed in the [feature request list](https://github.com/iamhyc/Overleaf-Workshop/issues?q=is%3Aissue+label%3A%22feature+request%22+).
- [x] The design of the feature does not require detailed discussion, or existing discussion with drawn conclusion can be found in [Discussions Area](https://github.com/iamhyc/Overleaf-Workshop/discussions) at: [paste the link here]

### Motivation
> Please give strong enough reason(s) why the feature is demanded.

The matching logic is different from overleaf website.

### Feature Description
> A clear and concise description of what you want to happen under what circumstance.

Current citation autocompletion matches the item starting from the first character. For example, I have an item with key `ullah2024llms`, I cannot match it with `llms` but only with `u...`. 

### [Optional] Additional context
> Please strike out any inappropriate items below. If you are not aware of the difference, please ignore this section.
- **Applicable Overleaf Edition**: Official / Community / Enterprise (Server Pro)
- **Applicable Extension Range**: Desktop Extension / Web Extension

**Comment by iamhyc** [comment]
Hi @wzunknown , thanks for the suggestion. We now provide a manually fuzzy match to provide the feature. Please check the temporary extension built here: https://github.com/iamhyc/Overleaf-Workshop/actions/runs/11103394949?pr=191

@QianrenLi Please help take care of the following up problems. I think the other completion items may also suffer from the same problem. The match is only a simple prefix matching w.r.t. the label for provided completion items.

**Comment by wzunknown** [comment]
Thanks @iamhyc, It works better! BTW I have another question, how to use the global search in the overleaf workspace? I find it is stuck and the icon keeps spinning when I try to search in the side bar.

**Comment by iamhyc** [comment]
> Thanks @iamhyc, It works better! BTW I have another question, how to use the global search in the overleaf workspace? I find it is stuck and the icon keeps spinning when I try to search in the side bar.

It is recorded in another issue #60, lack of vscode API support.
