### ISSUE TITLE
Outline doesn't show when using \chapter command

### ISSUE THREAD

**Issue by Zzzz2zy** [iamhyc/Overleaf-Workshop#193]
### Describe the bug
> A clear and concise description of what the bug is.

When I use \chapter command, the outline doesn't show as expected.
![outline](https://github.com/user-attachments/assets/a18be672-b674-467b-aa6b-192c0c6cd03b)

### Expected behavior
> A clear and concise description of what you expected to happen.

It should show the whole outline of my book/report/etc., just like overleaf website does.
![good](https://github.com/user-attachments/assets/ff48806b-1049-4535-9b5f-6c21e35a8bfe)

### How To Reproduce
> Detailed steps to reproduce the behavior.

Just write a book and use \chapter{...}.

### Environment
 - **Overleaf Workshop Extension version**: v0.13.2
 - **VS Code version**: 1.93.1
 - **Overleaf Edition**: Official

### [Optional] Developer Logs
> If applicable, please paste the logs inside the details section below.
> Please find the logs via: Title bar **"Help"** > **"Toggle Developer Tools"** > **"Console"**.

<details>
Logs are shown in "Describe the bug" and "Expected behavior".
</details>

**Comment by iamhyc** [comment]
@QianrenLi Please help take a look at it. Thanks you.

**Comment by QianrenLi** [comment]
Hi @Zzzz2zy, thanks for the report. Here's a quick fix https://github.com/iamhyc/Overleaf-Workshop/actions/runs/11136737840/artifacts/2003932577 for the chapter outline: [link to artifact]. Please give it a try and let me know if this resolves the issue.

**Comment by Zzzz2zy** [comment]
@QianrenLi Thanks for your reply. I have installed it, but the problem remains. :(

**Comment by QianrenLi** [comment]
Hi @Zzzz2zy, thank you for the test case. The issue arises because the file symbol provider fails when the input file does not exist. I've updated the patch to addresses this problem. You can find it here: https://github.com/iamhyc/Overleaf-Workshop/actions/runs/11155417845/artifacts/2009108156. Please give it a try and let me know if it resolves the issue.

**Comment by Zzzz2zy** [comment]
@QianrenLi It works! Thanks for your quick reply.
