### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by 70Alice** [iamhyc/Overleaf-Workshop#196]
### Disclaimer
> Please make sure all the items below is checked (i.e., prefixed with "- [x]")
- [x] The request feature has not been addressed in the [feature request list](https://github.com/iamhyc/Overleaf-Workshop/issues?q=is%3Aissue+label%3A%22feature+request%22+).
- [x] The design of the feature does not require detailed discussion, or existing discussion with drawn conclusion can be found in [Discussions Area](https://github.com/iamhyc/Overleaf-Workshop/discussions) at: [paste the link here]

### Motivation
> Please give strong enough reason(s) why the feature is demanded.
- Currently, this repository only supports Overleaf, which limits its usage to a single LaTeX platform. Supporting other LaTeX servers, would increase flexibility for users who prefer alternative platforms for LaTeX editing and compilation.

### Feature Description
> A clear and concise description of what you want to happen under what circumstance.
- Add support for additional LaTeX servers, such as [texpage.com](https://www.texpage.com/), so that users can use the repository with more than just Overleaf.

### [Optional] Additional context
> Please strike out any inappropriate items below. If you are not aware of the difference, please ignore this section.
- **Applicable Overleaf Edition**: Official / Community / Enterprise (Server Pro)
- **Applicable Extension Range**: Desktop Extension / Web Extension

**Comment by iamhyc** [comment]
The extension currently support adding self-hosted overleaf servers. Please follow the guidance here:

https://github.com/iamhyc/Overleaf-Workshop/blob/master/docs/wiki.md#add-new-server

**Comment by 70Alice** [comment]
Thank you very much for your prompt response and for all the effort you've put into developing the plugin. I greatly appreciate it!

However, I encountered an issue when trying to log into self-hosted Overleaf servers. Here's what happened:

When I selected password login, I entered my username and password, but nothing happened after submission.
When I tried cookie login, I entered the cookie, but received the following error messages: "login failed" and "failed to get user id."

Here is the cookie I used for login (with the SESSIONID partially hidden for security reasons):

_ga=GA1.1.1022757054.1718239756; fingerprint=24280d874d7641c335b7f6074bd0e8bf; Hm_lvt_7a99f35a28194ff70fa5255033bf49ca=1728378595; HMACCOUNT=FDD6CF6C9AEF6B13; acw_tc=9923ad1b17283863172281726e4dae5c7a7443cacc995b2c5e39bc6213; cdn_sec_tc=9923ad1b17283863172281726e4dae5c7a7443cacc995b2c5e39bc6213; SESSIONID=ee9f28077e74538c4e23c179f800f208***************; Hm_lpvt_7a99f35a28194ff70fa5255033bf49ca=1728386320; _ga_J3YE5G7DJT=GS1.1.1728386317.2.1.1728386327.0.0.0


I have already disabled my proxy software, and I can confirm that the self-hosted Overleaf server's URL (www.texpage.com) is reachable via ping.

I would appreciate any guidance or suggestions you may have to resolve this issue.










At 2024-10-08 00:58:53, "YCHONG" ***@***.***> wrote:

The extension currently support adding self-hosted overleaf servers. Please follow the guidance here:

https://github.com/iamhyc/Overleaf-Workshop/blob/master/docs/wiki.md#add-new-server

**Comment by iamhyc** [comment]
Huh, cause it is not a overleaf server. We do not support TexPage.
