### ISSUE TITLE
Main tex file name like "0.main.tex" will lead to some errors

### ISSUE THREAD

**Issue by wjfu99** [iamhyc/Overleaf-Workshop#197]
### Describe the bug

Recently, i found that if i use 0.main.tex as the main tex file with overleaf-workshop (open locally, collaborate with latex-workshop), several bugs will appear:
 - An empty 0.main.pdf file will appear in the remote overleaf project
 - overleaf-workshop will pull the remote empty pdf file in the next synchronization, which will lead the preview function provided by latex-workshop not works
 - Any tiny modification of the project seems to trigger the full amount synchronization

### Expected behavior
- Don't upload  the pdf file generated by latex-workshop to remote

### How To Reproduce
rename the main tex file to "0.main.tex" will reproduce it, I can fix this problem via renaming the main tex file to a regular name like "main.tex". Although this problem can be fixed easily, I open this issue to report this abnormal phenomenon.

### Environment
 - **Overleaf Workshop Extension version**: [e.g., 0.13.2]
 - **VS Code version**: [e.g. 1.94.0]
 - **Overleaf Edition**: Official

### [Optional] Developer Logs
> If applicable, please paste the logs inside the details section below.
> Please find the logs via: Title bar **"Help"** > **"Toggle Developer Tools"** > **"Console"**.

**Comment by iamhyc** [comment]
By default, only "/main.pdf" and "/output.pdf" are ignored at the root folder, so the generated "0.main.pdf" will be pushed to the server.

I do see some errors generated after renaming the main tex file. I will check it later.

**Comment by iamhyc** [comment]
Well, after some check, I find the printed errors could be ignored, and there is no "trigger the full amount synchronization" found in any case. I will mark this issue as cannot-reproduce until you could provide more details.
