### ISSUE TITLE
Colision with hsnips and LaTeX Workshop extension - no suggestion list when use Overleaf Workshop

### ISSUE THREAD

**Issue by vladan995** [iamhyc/Overleaf-Workshop#202]
I use hsnips extension from https://github.com/Oskar-Idland/hsnips which allows me to write Latex commands very fast. When I use Overleaf Workshop to work on documents on Overleaf servers my snippets don't work. There is no suggestions for any of snippets defined in hsnip extension. Only snippets that work are those which are "autoexpand," i.e. which does not request suggestion list.
When I work on documents which are not on Overleaf server it works perfectly.

 Environment
 - Overleaf Workshop Extension version:  0.14.1
 - VS Code version:  1.93.1
 - **Overleaf Edition**: Official / Community / Enterprise (Server Pro)

**Comment by vladan995** [comment]
It also blocks suggestions from Latex Workshop extension. There no suggestions at all.

**Comment by iamhyc** [comment]
@QianrenLi Please help have a look at it.

**Comment by iamhyc** [comment]
@vladan995 It may be related to the [virtual workspace](https://code.visualstudio.com/api/extension-guides/virtual-workspaces) mechanism in vscode. You can try "open project locally" instead, following the guidance here: https://github.com/iamhyc/Overleaf-Workshop/blob/master/docs/wiki.md#open-project-locally

**Comment by vladan995** [comment]
That solves the problem. Thanks.
