### ISSUE TITLE
[Feature Request] preview automatically resets to the first page after build.

### ISSUE THREAD

**Issue by Mark-htmlgogogo** [iamhyc/Overleaf-Workshop#204]
In the Overleaf workshop, every time I re-build the .`tex` file, the preview automatically resets to the first page rather than maintaining the current view. I'm not sure if this behavior can be configured.

For instance, if I'm working in the middle of the `.tex` file with the preview on page 5, modifying and re-building the file causes the preview to refresh and jump back to the first page.

**Comment by iamhyc** [comment]
The default behavior should keep with the current page view when refresh.

Please attach the developer logs so we may figure out why.
> Please find the logs via: Title bar **"Help"** > **"Toggle Developer Tools"** > **"Console"**.
