### ISSUE TITLE
Could not see the projects in overleaf.com

### ISSUE THREAD

**Issue by iGFalouji** [iamhyc/Overleaf-Workshop#22]
I followed the instructions of cookies login to overleaf.com. I can see no project, neither can I create any project. I get the error:
404:Page not found-overleaf, online ...

**Comment by iamhyc** [comment]
Please make sure the server address is "https://www.overleaf.com" and use "Login with Cookies".

> For how to extract cookies, please refer to [how-to-login-with-cookies](https://github.com/iamhyc/Overleaf-Workshop#how-to-login-with-cookies) on README page.

**Comment by iamhyc** [comment]
@iGFalouji As there is no more feedback, I will close this issue now.

Please feel free to re-open it or create a new issue if your problem has not been solved.

**Comment by iamhyc** [comment]
Hi @iGFalouji , I just realized that you encounter the same problem as in #26 .

Please remove your overleaf sever firstly and use the correct server address: `https://www.overleaf.com`.

Be aware that both `https://` and `www` are necessary for access to the correct overleaf server.
