### ISSUE TITLE
Horizontal line of pdf viewer in Dark Theme

### ISSUE THREAD

**Issue by rhfeiyang** [iamhyc/Overleaf-Workshop#25]
![c963b538-5399-4cf2-bf35-4d51ad70ec28](https://github.com/iamhyc/Overleaf-Workshop/assets/99195158/930a4adf-a0ea-4dfb-966d-ecbe236ca5f4)
In white theme, the horizontal line is shown normally, but in Dark theme, it is still black:
![9d74e075-fc93-48a8-9b6f-d15acc64d55d](https://github.com/iamhyc/Overleaf-Workshop/assets/99195158/68b8a0c3-2c67-4852-b968-142e7f7da125)
Can you fix it?

**Comment by iamhyc** [comment]
I will put it on plan.

However, as `pdf.js` draw the line together with the figures not the text, I am not sure whether it can be fixed.

**Comment by rhfeiyang** [comment]
what about using css filter?
https://blog.csdn.net/xuhss_com/article/details/124089741

**Comment by iamhyc** [comment]
> what about using css filter? https://blog.csdn.net/xuhss_com/article/details/124089741

We don't use filter, it hurts images.

**Comment by iamhyc** [comment]
Hi @rhfeiyang , I have done a quick fix, which should work for common cases. I still need to design more tests to make the fix stable. I have packed a temporary version attached and you can have a try.

![](https://github.com/iamhyc/Overleaf-Workshop/assets/9068301/99f21fa4-0da2-43e1-bc3e-6f27421275cc)

[overleaf-workshop-0.6.0-alpha.1.vsix.zip](https://github.com/iamhyc/Overleaf-Workshop/files/13692271/overleaf-workshop-0.6.0-alpha.1.vsix.zip)

**Comment by iamhyc** [comment]
The fix is included in `v0.6.0`. The color of some math symbols are not fixed, e.g. `\mathbbm`.
As there is no color hint for it (`paintImageMaskXObject`), I prefer it still uses the default black color.

**Comment by iamhyc** [comment]
Seems like it breaks default and bright theme ... will fix it later today 😕

**Comment by rhfeiyang** [comment]
> Seems like it breaks default and bright theme ... will fix it later today 😕

Yes. And at the first render, it becomes totally white:
![image](https://github.com/iamhyc/Overleaf-Workshop/assets/99195158/bbe2eb0d-271b-434b-a55c-9acb085d353b)
Until I change to the dark theme.
And I continue to change to white:
![image](https://github.com/iamhyc/Overleaf-Workshop/assets/99195158/89a74925-52e7-4ef9-b421-2362cad3b838)

BTW, don't you think the blue color of links in dark mode is too dark?
![image](https://github.com/iamhyc/Overleaf-Workshop/assets/99195158/4d62e01b-078b-4b86-8e40-9e215b1bb0ad)

**Comment by iamhyc** [comment]
> > Seems like it breaks default and bright theme ... will fix it later today 😕
> 
> Yes. And at the first render, it becomes totally white:

Solved. Please use the latest `v0.6.1`.

> BTW, don't you think the blue color of links in dark mode is too dark?

In the current color scheme, we only replace the color `#000000` and `#FFFFFF` but not mapping the entire color space, so it would look weird visually.

We would like to accept any improvement contribution after `v0.8.0` when the contribution guidance and github actions would be setup then.
