### ISSUE TITLE
404 problem

### ISSUE THREAD

**Issue by liuss47** [iamhyc/Overleaf-Workshop#26]
I used cookies to login but cannot load any of my projects.
Here is  the code:
404: <!DOCTYPE html><html lang="en"><head><title>Page Not Found - Overleaf, Online LaTeX Editor</title><meta name="twitter:title" content="Page Not Found"><meta name="og:title" content="Page Not Found"><meta name="description" content="An online LaTeX editor that’s easy to use. No installation, real-time collaboration, version control, hundreds of LaTeX templates, and more."><meta itemprop="description" content="An online LaTeX editor that’s easy to use. No installation, real-time collaboration, version control, hundreds of LaTeX templates, and more."><meta itemprop="image" content="https://cdn.overleaf.com/img/ol-brand/overleaf_og_logo.png"><meta name="image" content="https://cdn.overleaf.com/img/ol-brand/overleaf_og_logo.png"><meta itemprop="name" content="Overleaf, the Online LaTeX Editor"><meta name="twitter:card" content="summary"><meta name="twitter:site" content="@overleaf"><meta name="twitter:description" content="An online LaTeX editor that’s easy to use. No installation, real-time collaboration, version control, hundreds of LaTeX templates, and more."><meta name="twitter:image" content="https://cdn.overleaf.com/img/ol-brand/overleaf_og_logo.png"><meta property="fb:app_id" content="400474170024644"><meta property="og:description" content="An online LaTeX editor that’s easy to use. No installation, real-time collaboration, version control, hundreds of LaTeX templates, and more."><meta property="og:image" content="https://cdn.overleaf.com/img/ol-brand/overleaf_og_logo.png"><meta property="og:type" content="website"><meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes"><meta name="apple-mobile-web-app-capable" content="yes"><meta name="apple-mobile-web-app-status-bar-style" content="black-translucent"><link rel="icon" href="/favicon.ico"><link rel="icon" sizes="192x192" href="/touch-icon-192x192.png"><link rel="apple-touch-icon-precomposed" href="/apple-touch-icon-precomposed.png"><link rel="mask-icon" href="/mask-favicon.svg" color="#138A07"><link rel="stylesheet" href="https://cdn.overleaf.com/stylesheets/main-style-d8697fd399e520c523e2.css" id="main-stylesheet"><link rel="alternate" href="https://www.overleaf.com/project/652f5f03b214b7f2ec241a2buser/projects" hreflang="en"><link rel="alternate" href="https://cs.overleaf.com/project/652f5f03b214b7f2ec241a2buser/projects" hreflang="cs"><link rel="alternate" href="https://es.overleaf.com/project/652f5f03b214b7f2ec241a2buser/projects" hreflang="es"><link rel="alternate" href="https://pt.overleaf.com/project/652f5f03b214b7f2ec241a2buser/projects" hreflang="pt"><link rel="alternate" href="https://fr.overleaf.com/project/652f5f03b214b7f2ec241a2buser/projects" hreflang="fr"><link rel="alternate" href="https://de.overleaf.com/project/652f5f03b214b7f2ec241a2buser/projects" hreflang="de"><link rel="alternate" href="https://sv.overleaf.com/project/652f5f03b214b7f2ec241a2buser/projects" hreflang="sv"><link rel="alternate" href="https://tr.overleaf.com/project/652f5f03b214b7f2ec241a2buser/projects" hreflang="tr"><link rel="alternate" href="https://it.overleaf.com/project/652f5f03b214b7f2ec241a2buser/projects" hreflang="it"><link rel="alternate" href="https://cn.overleaf.com/project/652f5f03b214b7f2ec241a2buser/projects" hreflang="zh-CN"><link rel="alternate" href="https://no.overleaf.com/project/652f5f03b214b7f2ec241a2buser/projects" hreflang="no"><link rel="alternate" href="https://ru.overleaf.com/project/652f5f03b214b7f2ec241a2buser/projects" hreflang="ru"><link rel="alternate" href="https://da.overleaf.com/project/652f5f03b214b7f2ec241a2buser/projects" hreflang="da"><link rel="alternate" href="https://ko.overleaf.com/project/652f5f03b214b7f2ec241a2buser/projects" hreflang="ko"><link rel="alternate" href="https://ja.overleaf.com/project/652f5f03b214b7f2ec241a2buser/projects" hreflang="ja"><script type="text/javascript" nonce="SrnNwXz9SVS8HMK174OyjQ==" id="ga-loader" data-ga-token="UA-112092690-1" data-ga-token-v4="G-RV4YBCCCWJ" data-cookie-domain=".overleaf.com">var gaSettings = document.querySelector('#ga-loader').dataset;
var gaid = gaSettings.gaTokenV4;
var gaToken = gaSettings.gaToken;
var cookieDomain = gaSettings.cookieDomain;
if(gaid) {
    window.dataLayer = window.dataLayer || [];
    function gtag(){
        dataLayer.push(arguments);
    }
    gtag('js', new Date());
    gtag('config', gaid, { 'anonymize_ip': true });
}
if (gaToken) {
    window.ga = window.ga || function () {
        (window.ga.q = window.ga.q || []).push(arguments);
    }, window.ga.l = 1 * new Date();
}
var loadGA = window.olLoadGA = function() {
    if (gaid) {
        var s = document.createElement('script');
        s.setAttribute('async', 'async');
        s.setAttribute('src', 'https://www.googletagmanager.com/gtag/js?id=' + gaid);
        document.querySelector('head').append(s);
    } 
    if (gaToken) {
        (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
        m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
        ga('create', gaToken, cookieDomain.replace(/^\./, ""));
        ga('set', 'anonymizeIp', true);
        ga('send', 'pageview');
    }
};
// Check if consent given (features/cookie-banner)
var oaCookie = document.cookie.split('; ').find(function(cookie) {
    return cookie.startsWith('oa=');
});
if(oaCookie) {
    var oaCookieValue = oaCookie.split('=')[1];
    if(oaCookieValue === '1') {
        loadGA();
    }
}
</script><meta name="ol-csrfToken" content="ACrzBvEf-ilna-Ca4EVd2TGZJeEOtpa7Lsug"><meta name="ol-baseAssetPath" content="https://cdn.overleaf.com/"><meta name="ol-usersEmail" content="liusishuo4477@gmail.com"><meta name="ol-sharelatex" data-type="json" content="{&quot;siteUrl&quot;:&quot;https://www.overleaf.com&quot;}"><meta name="ol-ab" data-type="json" content="{}"><meta name="ol-user_id" content="63319d16aec1f977c6823790"><meta name="ol-i18n" data-type="json" content="{&quot;currentLangCode&quot;:&quot;en&quot;}"><meta name="ol-ExposedSettings" data-type="json" content="{&quot;isOverleaf&quot;:true,&quot;appName&quot;:&quot;Overleaf&quot;,&quot;adminEmail&quot;:&quot;support@overleaf.com&quot;,&quot;dropboxAppName&quot;:&quot;Overleaf&quot;,&quot;hasAffiliationsFeature&quot;:true,&quot;hasSamlFeature&quot;:true,&quot;samlInitPath&quot;:&quot;/saml/ukamf/init&quot;,&quot;hasLinkUrlFeature&quot;:true,&quot;hasLinkedProjectFileFeature&quot;:true,&quot;hasLinkedProjectOutputFileFeature&quot;:true,&quot;siteUrl&quot;:&quot;https://www.overleaf.com&quot;,&quot;emailConfirmationDisabled&quot;:false,&quot;maxEntitiesPerProject&quot;:2000,&quot;maxUploadSize&quot;:52428800,&quot;projectUploadTimeout&quot;:120000,&quot;recaptchaSiteKey&quot;:&quot;6LebiTwUAAAAAMuPyjA4pDA4jxPxPe2K9_ndL74Q&quot;,&quot;recaptchaDisabled&quot;:{&quot;invite&quot;:true,&quot;login&quot;:false,&quot;passwordReset&quot;:false,&quot;register&quot;:false,&quot;addEmail&quot;:false},&quot;textExtensions&quot;:[&quot;tex&quot;,&quot;latex&quot;,&quot;sty&quot;,&quot;cls&quot;,&quot;bst&quot;,&quot;bib&quot;,&quot;bibtex&quot;,&quot;txt&quot;,&quot;tikz&quot;,&quot;mtx&quot;,&quot;rtex&quot;,&quot;md&quot;,&quot;asy&quot;,&quot;lbx&quot;,&quot;bbx&quot;,&quot;cbx&quot;,&quot;m&quot;,&quot;lco&quot;,&quot;dtx&quot;,&quot;ins&quot;,&quot;ist&quot;,&quot;def&quot;,&quot;clo&quot;,&quot;ldf&quot;,&quot;rmd&quot;,&quot;lua&quot;,&quot;gv&quot;,&quot;mf&quot;,&quot;yml&quot;,&quot;yaml&quot;,&quot;lhs&quot;,&quot;mk&quot;,&quot;xmpdata&quot;],&quot;editableFilenames&quot;:[&quot;latexmkrc&quot;,&quot;.latexmkrc&quot;,&quot;makefile&quot;,&quot;gnumakefile&quot;],&quot;validRootDocExtensions&quot;:[&quot;tex&quot;,&quot;Rtex&quot;,&quot;ltx&quot;,&quot;Rnw&quot;],&quot;sentryAllowedOriginRegex&quot;:&quot;^(https://[a-z]+\\\\.overleaf.com|https://cdn.overleaf.com|https://compiles.overleafusercontent.com)/&quot;,&quot;sentryDsn&quot;:&quot;https://4f0989f11cb54142a5c3d98b421b930a@app.getsentry.com/34706&quot;,&quot;sentryEnvironment&quot;:&quot;production&quot;,&quot;sentryRelease&quot;:&quot;2d0f965746c45142f0927d06a23759aa5ff52c1a&quot;,&quot;enableSubscriptions&quot;:true,&quot;gaToken&quot;:&quot;UA-112092690-1&quot;,&quot;gaTokenV4&quot;:&quot;G-RV4YBCCCWJ&quot;,&quot;cookieDomain&quot;:&quot;.overleaf.com&quot;,&quot;templateLinks&quot;:[{&quot;name&quot;:&quot;Academic Journal&quot;,&quot;url&quot;:&quot;/gallery/tagged/academic-journal&quot;,&quot;trackingKey&quot;:&quot;academic-journal&quot;},{&quot;name&quot;:&quot;Book&quot;,&quot;url&quot;:&quot;/gallery/tagged/book&quot;,&quot;trackingKey&quot;:&quot;book&quot;},{&quot;name&quot;:&quot;Formal Letter&quot;,&quot;url&quot;:&quot;/gallery/tagged/formal-letter&quot;,&quot;trackingKey&quot;:&quot;formal-letter&quot;},{&quot;name&quot;:&quot;Homework Assignment&quot;,&quot;url&quot;:&quot;/gallery/tagged/homework&quot;,&quot;trackingKey&quot;:&quot;homework-assignment&quot;},{&quot;name&quot;:&quot;Poster&quot;,&quot;url&quot;:&quot;/gallery/tagged/poster&quot;,&quot;trackingKey&quot;:&quot;poster&quot;},{&quot;name&quot;:&quot;Presentation&quot;,&quot;url&quot;:&quot;/gallery/tagged/presentation&quot;,&quot;trackingKey&quot;:&quot;presentation&quot;},{&quot;name&quot;:&quot;Project / Lab Report&quot;,&quot;url&quot;:&quot;/gallery/tagged/report&quot;,&quot;trackingKey&quot;:&quot;lab-report&quot;},{&quot;name&quot;:&quot;Résumé / CV &quot;,&quot;url&quot;:&quot;/gallery/tagged/cv&quot;,&quot;trackingKey&quot;:&quot;cv&quot;},{&quot;name&quot;:&quot;Thesis&quot;,&quot;url&quot;:&quot;/gallery/tagged/thesis&quot;,&quot;trackingKey&quot;:&quot;thesis&quot;},{&quot;name&quot;:&quot;view_all&quot;,&quot;url&quot;:&quot;/latex/templates&quot;,&quot;trackingKey&quot;:&quot;view-all&quot;}],&quot;labsEnabled&quot;:false}"><meta name="ol-splitTestVariants" data-type="json" content="{&quot;design-system-updates&quot;:&quot;enabled&quot;,&quot;features-page&quot;:&quot;new&quot;}"><meta name="ol-splitTestInfo" data-type="json" content="{&quot;design-system-updates&quot;:{&quot;phase&quot;:&quot;release&quot;,&quot;badgeInfo&quot;:{&quot;url&quot;:&quot;&quot;,&quot;tooltipText&quot;:&quot;&quot;}},&quot;features-page&quot;:{&quot;phase&quot;:&quot;release&quot;,&quot;badgeInfo&quot;:{&quot;url&quot;:&quot;&quot;,&quot;tooltipText&quot;:&quot;&quot;}}}"><meta name="ol-algolia" data-type="json" content="{&quot;appId&quot;:&quot;SK53GL4JLY&quot;,&quot;apiKey&quot;:&quot;9ac63d917afab223adbd2cd09ad0eb17&quot;,&quot;indexes&quot;:{&quot;wiki&quot;:&quot;learn-wiki&quot;,&quot;gallery&quot;:&quot;gallery-production&quot;}}"><meta name="ol-isManagedAccount" data-type="boolean"></head><body ng-csp="no-unsafe-eval"><a class="skip-to-content" href="#main-content">Skip to content</a><nav class="navbar navbar-default navbar-main"><div class="container-fluid"><div class="navbar-header"><button class="navbar-toggle collapsed" type="button" data-toggle="collapse" data-target="[data-ol-navbar-main-collapse]" aria-label="Toggle Navigation"><i class="fa fa-bars" aria-hidden="true"></i></button><a class="navbar-brand" href="/" aria-label="Overleaf"></a></div><div class="navbar-collapse collapse" data-ol-navbar-main-collapse><ul class="nav navbar-nav navbar-right"><li class="dropdown subdued"><a class="dropdown-toggle" href="#" role="button" aria-haspopup="true" aria-expanded="false" data-toggle="dropdown">Features & Benefits<span class="caret"></span></a><ul class="dropdown-menu"><li></li><li><a href="/about/features-overview" event-tracking="menu-clicked-premium-features" event-tracking-mb="true" event-tracking-trigger="click" event-segmentation="{&quot;splitTest&quot;:&quot;features-page&quot;,&quot;splitTestVariant&quot;:&quot;new&quot;,&quot;locationInPage&quot;:&quot;main navigation&quot;}">Features</a></li><li><a href="/for/authors" event-tracking="menu-clicked-authors" event-tracking-mb="true" event-tracking-trigger="click">For Writing</a></li><li><a href="/for/groups" event-tracking="menu-clicked-groups" event-tracking-mb="true" event-tracking-trigger="click">For Groups</a></li><li><a href="/for/edu" event-tracking="menu-clicked-edu" event-tracking-mb="true" event-tracking-trigger="click">For Teaching</a></li><li><a href="/for/universities" event-tracking="menu-clicked-universities" event-tracking-mb="true" event-tracking-trigger="click">For Universities</a></li><li><a href="/for/publishers" event-tracking="menu-clicked-publishers" event-tracking-mb="true" event-tracking-trigger="click">For Publishers</a></li><li><a href="/for/enterprises" event-tracking="menu-clicked-enterprises" event-tracking-mb="true" event-tracking-trigger="click">For Enterprises</a></li></ul></li><li class="subdued"><a class="subdued" href="/latex/templates" event-tracking="menu-clicked-templates" event-tracking-mb="true" event-tracking-trigger="click">Templates</a></li><li class="subdued"><a class="subdued" href="/user/subscription/plans" event-tracking="menu-clicked-plans" event-tracking-mb="true" event-tracking-trigger="click">Plans &amp; Pricing</a></li><li class="dropdown subdued"><a class="dropdown-toggle" href="#" role="button" aria-haspopup="true" aria-expanded="false" data-toggle="dropdown">Help<span class="caret"></span></a><ul class="dropdown-menu"><li><a href="/learn" event-tracking="menu-clicked-learn" event-tracking-mb="true" event-tracking-trigger="click">Documentation</a></li><li><a data-ol-open-contact-form-modal="contact-us" href><span event-tracking="menu-clicked-contact" event-tracking-mb="true" event-tracking-trigger="click">Contact Us</span></a></li></ul></li><li><a href="/project">Projects</a></li><li class="dropdown"><a class="dropdown-toggle" href="#" role="button" aria-haspopup="true" aria-expanded="false" data-toggle="dropdown">Account<span class="caret"></span></a><ul class="dropdown-menu"><li><div class="subdued">liusishuo4477@gmail.com</div></li><li class="divider hidden-xs hidden-sm"></li><li><a href="/user/settings">Account Settings</a></li><li><a href="/user/subscription">Subscription</a></li><li class="divider hidden-xs hidden-sm"></li><li><form method="POST" action="/logout"><input name="_csrf" type="hidden" value="ACrzBvEf-ilna-Ca4EVd2TGZJeEOtpa7Lsug"><button class="btn-link text-left dropdown-menu-button">Log Out</button></form></li></ul></li></ul></div></div></nav><main class="content content-alt" id="main-content"><div class="container"><div class="error-container"><div class="error-details"><p class="error-status">Not found</p><p class="error-description">Sorry, we can’t find the page you are looking for.</p><p class="error-actions"><a class="error-btn" href="/">Home</a></p></div></div></div></main><footer class="fat-footer hidden-print"><div class="fat-footer-container" role="navigation" aria-label="Footer navigation"><div class="fat-footer-sections"><div class="footer-section" id="footer-brand"><a class="footer-brand" href="/" aria-label="Overleaf"></a></div><div class="footer-section"><h2 class="footer-section-heading">About</h2><ul class="list-unstyled"><li><a href="/about">About us</a></li><li><a href="/about/values">Our values</a></li><li><a href="/about/careers">Careers</a></li><li><a href="/for/press">Press &amp; awards</a></li><li><a href="/blog">Blog</a></li></ul></div><div class="footer-section"><h2 class="footer-section-heading">Learn</h2><ul class="list-unstyled"><li><a href="/learn/latex/Learn_LaTeX_in_30_minutes">LaTeX in 30 minutes</a></li><li><a href="/latex/templates">Templates</a></li><li><a href="/events/webinars">Webinars</a></li><li><a href="/learn/latex/Tutorials">Tutorials</a></li><li><a href="/learn/latex/Inserting_Images">How to insert images</a></li><li><a href="/learn/latex/Tables">How to create tables</a></li></ul></div><div class="footer-section"><h2 class="footer-section-heading">Plans &amp; pricing</h2><ul class="list-unstyled"><li><a href="/about/features-overview" event-tracking="features-page-link" event-tracking-mb="true" event-tracking-trigger="click" event-segmentation="{&quot;splitTest&quot;:&quot;features-page&quot;,&quot;splitTestVariant&quot;:&quot;new&quot;,&quot;locationInPage&quot;:&quot;footer&quot;}">Features</a></li><li><a href="/user/subscription/plans?itm_referrer=footer-for-indv-groups">For individuals &amp; groups</a></li><li><a href="/for/enterprises">For enterprise</a></li><li><a href="/for/universities">For Universities</a></li><li><a href="/user/subscription/plans?itm_referrer=footer-for-students#view=student">For students</a></li></ul></div><div class="footer-section"><h2 class="footer-section-heading">Get involved</h2><ul class="list-unstyled"><li><a href="/for/community/advisors">Become an Overleaf advisor</a></li><li><a href="https://forms.gle/67PSpN1bLnjGCmPQ9">Let us know what you think</a></li><li><a href="/beta/participate">Join beta program</a></li><li><a href="/user/bonus">Refer a friend</a></li></ul></div><div class="footer-section"><h2 class="footer-section-heading">Help</h2><ul class="list-unstyled"><li><a href="/learn">Documentation </a></li><li><a href="/contact">Contact us  </a></li><li><a href="https://status.overleaf.com/">Website status</a></li></ul></div></div><div class="fat-footer-base"><div class="fat-footer-base-section fat-footer-base-meta"><div class="fat-footer-base-item"> <div class="fat-footer-base-copyright">© 2023 Overleaf</div><a href="/legal">Privacy and Terms</a></div><ul class="fat-footer-base-item list-unstyled fat-footer-base-language"><li class="dropdown dropup subdued language-picker" dropdown><a class="dropdown-toggle" id="language-picker-toggle" href="#" dropdown-toggle data-ol-lang-selector-tooltip data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false" aria-label="Select Language" tooltip="Language" title="Language"><i class="fa fa-fw fa-language"></i>
English</a><ul class="dropdown-menu" role="menu" aria-labelledby="language-picker-toggle"><li class="dropdown-header">Language</li><li class="lngOption"><a class="menu-indent" href="https://www.overleaf.com/project/652f5f03b214b7f2ec241a2buser/projects" role="menuitem">English</a></li><li class="lngOption"><a class="menu-indent" href="https://cs.overleaf.com/project/652f5f03b214b7f2ec241a2buser/projects" role="menuitem">Čeština</a></li><li class="lngOption"><a class="menu-indent" href="https://es.overleaf.com/project/652f5f03b214b7f2ec241a2buser/projects" role="menuitem">Español</a></li><li class="lngOption"><a class="menu-indent" href="https://pt.overleaf.com/project/652f5f03b214b7f2ec241a2buser/projects" role="menuitem">Português</a></li><li class="lngOption"><a class="menu-indent" href="https://fr.overleaf.com/project/652f5f03b214b7f2ec241a2buser/projects" role="menuitem">Français</a></li><li class="lngOption"><a class="menu-indent" href="https://de.overleaf.com/project/652f5f03b214b7f2ec241a2buser/projects" role="menuitem">Deutsch</a></li><li class="lngOption"><a class="menu-indent" href="https://sv.overleaf.com/project/652f5f03b214b7f2ec241a2buser/projects" role="menuitem">Svenska</a></li><li class="lngOption"><a class="menu-indent" href="https://tr.overleaf.com/project/652f5f03b214b7f2ec241a2buser/projects" role="menuitem">Türkçe</a></li><li class="lngOption"><a class="menu-indent" href="https://it.overleaf.com/project/652f5f03b214b7f2ec241a2buser/projects" role="menuitem">Italiano</a></li><li class="lngOption"><a class="menu-indent" href="https://cn.overleaf.com/project/652f5f03b214b7f2ec241a2buser/projects" role="menuitem">简体中文</a></li><li class="lngOption"><a class="menu-indent" href="https://no.overleaf.com/project/652f5f03b214b7f2ec241a2buser/projects" role="menuitem">Norsk</a></li><li class="lngOption"><a class="menu-indent" href="https://ru.overleaf.com/project/652f5f03b214b7f2ec241a2buser/projects" role="menuitem">Русский</a></li><li class="lngOption"><a class="menu-indent" href="https://da.overleaf.com/project/652f5f03b214b7f2ec241a2buser/projects" role="menuitem">Dansk</a></li><li class="lngOption"><a class="menu-indent" href="https://ko.overleaf.com/project/652f5f03b214b7f2ec241a2buser/projects" role="menuitem">한국어</a></li><li class="lngOption"><a class="menu-indent" href="https://ja.overleaf.com/project/652f5f03b214b7f2ec241a2buser/projects" role="menuitem">日本語</a></li></ul></li></ul></div><div class="fat-footer-base-section fat-footer-base-social"><div class="fat-footer-base-item"><a class="fat-footer-social" href="https://twitter.com/overleaf"><i class="fa fa-twitter-square" aria-hidden="true"></i><div class="sr-only">Overleaf on Twitter</div></a><a class="fat-footer-social" href="https://www.facebook.com/overleaf.editor"><i class="fa fa-facebook-square" aria-hidden="true"></i><div class="sr-only">Overleaf on Facebook</div></a><a class="fat-footer-social" href="https://www.linkedin.com/company/writelatex-limited"><i class="fa fa-linkedin-square" aria-hidden="true"></i><div class="sr-only">Overleaf on LinkedIn</div></a></div></div></div></div></footer><div class="cookie-banner hidden-print hidden"><div class="cookie-banner-content">We only use cookies for essential purposes and to improve your experience on our site. You can find out more in our <a href="/legal#Cookies">cookie policy</a>.</div><div class="cookie-banner-actions"><button class="btn btn-link btn-sm" type="button" data-ol-cookie-banner-set-consent="essential">Essential cookies only</button><button class="btn btn-primary btn-sm" type="button" data-ol-cookie-banner-set-consent="all">Accept all cookies</button></div></div><div class="modal fade" tabindex="-1" role="dialog" data-ol-contact-form-modal="contact-us"><div class="modal-dialog" role="document"><div class="modal-content"><div class="modal-header"><button class="close" type="button" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button><h4 class="modal-title">Contact Us</h4></div><div class="modal-body contact-us-modal"><form data-ol-async-form data-ol-contact-form data-ol-contact-form-with-search name="contactForm" role="form" aria-label="Contact Us" action="/support"><input name="inbox" type="hidden" value="support"><span data-ol-not-sent><div data-ol-form-messages="" role="alert"></div><label>Subject</label><div class="form-group"><input class="field text medium span8 form-control" aria-label="Subject" name="subject" required autocomplete="off" maxlength="255"></div><div class="contact-suggestions" data-ol-search-results-wrapper hidden><p class="contact-suggestion-label" aria-live="polite">Have you checked our <a href="/learn/kb" target="_blank">knowledge base</a>?</p><ul class="contact-suggestion-list" data-ol-search-results aria-role="region" aria-label="Help articles matching your subject"></ul></div><input type="hidden" name="email" value="liusishuo4477@gmail.com"><label class="desc" id="title12">Affected project URL (Optional)</label><div class="form-group"><input class="field text medium span8 form-control" name="projectUrl" aria-label="Affected project URL Optional"></div><label class="desc">Message</label><div class="form-group"><textarea class="field text medium span8 form-control" aria-label="Message" name="message" required type="text"></textarea></div><div class="form-group hidden"><input class="field text medium span8 form-control" aria-label="important message" name="important_message"></div><div class="form-group text-center"><button class="btn-primary btn btn-lg" type="submit" data-ol-disabled-inflight event-tracking="form-submitted-contact-us" event-tracking-mb="true" event-tracking-trigger="click"><span data-ol-inflight="idle" aria-label="Contact Us">Contact Us</span><span hidden data-ol-inflight="pending" aria-label="Sending">Sending…</span></button></div></span><span data-ol-sent hidden><p>Message sent! Our team will review it and reply by email.</p><p>Email: liusishuo4477@gmail.com</p></span></form></div></div></div></div></body><script type="text/javascript" nonce="SrnNwXz9SVS8HMK174OyjQ==" src="https://cdn.overleaf.com/js/3296-1b55642e46033040fe17.js"></script><script type="text/javascript" nonce="SrnNwXz9SVS8HMK174OyjQ==" src="https://cdn.overleaf.com/js/3845-0fdb827b2e4b37653df2.js"></script><script type="text/javascript" nonce="SrnNwXz9SVS8HMK174OyjQ==" src="https://cdn.overleaf.com/js/8182-b454d482e496ceeb066e.js"></script><script type="text/javascript" nonce="SrnNwXz9SVS8HMK174OyjQ==" src="https://cdn.overleaf.com/js/5743-daaa197941c6f383952e.js"></script><script type="text/javascript" nonce="SrnNwXz9SVS8HMK174OyjQ==" src="https://cdn.overleaf.com/js/6029-79c5b2c3e56947add815.js"></script><script type="text/javascript" nonce="SrnNwXz9SVS8HMK174OyjQ==" src="https://cdn.overleaf.com/js/3297-4a9cff63ad93ebfeba51.js"></script><script type="text/javascript" nonce="SrnNwXz9SVS8HMK174OyjQ==" src="https://cdn.overleaf.com/js/8306-15645705d1df6b9f845c.js"></script><script type="text/javascript" nonce="SrnNwXz9SVS8HMK174OyjQ==" src="https://cdn.overleaf.com/js/8356-f66ace891655a7b8a416.js"></script><script type="text/javascript" nonce="SrnNwXz9SVS8HMK174OyjQ==" src="https://cdn.overleaf.com/js/7416-dfa90b869d89bd67bbd9.js"></script><script type="text/javascript" nonce="SrnNwXz9SVS8HMK174OyjQ==" src="https://cdn.overleaf.com/js/9517-97cb94c0951e6b11d0c5.js"></script><script type="text/javascript" nonce="SrnNwXz9SVS8HMK174OyjQ==" src="https://cdn.overleaf.com/js/5946-8031ab826fa5a11b229f.js"></script><script type="text/javascript" nonce="SrnNwXz9SVS8HMK174OyjQ==" src="https://cdn.overleaf.com/js/3989-6b559096c21ffb8ad3c9.js"></script><script type="text/javascript" nonce="SrnNwXz9SVS8HMK174OyjQ==" src="https://cdn.overleaf.com/js/86-4ad2287281bdcc0a63d7.js"></script><script type="text/javascript" nonce="SrnNwXz9SVS8HMK174OyjQ==" src="https://cdn.overleaf.com/js/4404-b17b00ae699480f4423a.js"></script><script type="text/javascript" nonce="SrnNwXz9SVS8HMK174OyjQ==" src="https://cdn.overleaf.com/js/6181-9293524a9326bfddb202.js"></script><script type="text/javascript" nonce="SrnNwXz9SVS8HMK174OyjQ==" src="https://cdn.overleaf.com/js/4559-ffd51ed88a65e170ce09.js"></script><script type="text/javascript" nonce="SrnNwXz9SVS8HMK174OyjQ==" src="https://cdn.overleaf.com/js/8684-72071de9de41c7ac47f9.js"></script><script type="text/javascript" nonce="SrnNwXz9SVS8HMK174OyjQ==" src="https://cdn.overleaf.com/js/marketing-6a70b51985aa54b8136a.js"></script><script type="text/javascript" nonce="SrnNwXz9SVS8HMK174OyjQ==">//- Look for bundle
var cdnBlocked = typeof Frontend === 'undefined'
//- Prevent loops
var noCdnAlreadyInUrl = window.location.href.indexOf("nocdn=true") != -1
if (cdnBlocked && !noCdnAlreadyInUrl && navigator.userAgent.indexOf("Googlebot") == -1) {
	//- Set query param, server will not set CDN url
	window.location.search += "&nocdn=true";
}</script></html>

**Comment by iamhyc** [comment]
A quick checklist for you:
- [ ] make sure the server address is exactly `https://www.overleaf.com`
- [ ] make sure the cookie input is in the format like `overleaf_session2=...`

Let me know if it still does not work.

**Comment by liuss47** [comment]
Yes, they are both right.
And It seems sign in successfully but no project loading

**Comment by iamhyc** [comment]
![图片](https://github.com/iamhyc/Overleaf-Workshop/assets/9068301/e062610f-acfc-4e1a-aadf-d201a13b4f27)

A successful login should allow you to list the projects.

Is the above error message shown in a popup window from vscode when you login?

**Comment by iamhyc** [comment]
And if your cookies in browser show some more items than "overleaf_session2", e.g., `overleaf_session2=...; oa=...; <key>=<value>`, you only need to have `overleaf_session2=...` as input for login.

**Comment by liuss47** [comment]
Yes, the logo changed to you shown here but no project loaded.When I click reload I get the above message.
Besides, I used some network agent service I do not know its impact

**Comment by iamhyc** [comment]
> Yes, the logo changed to you shown here but no project loaded.When I click reload I get the above message. Besides, I used some network agent service I do not know its impact

Weird. So your login is successful but the project fetch failed.

Have you tried to login again and with a new cookie?

**Comment by liuss47** [comment]
> > 是的，徽标更改为此处显示的您，但未加载项目。当我单击“重新加载”时，我收到上述消息。另外，我使用了一些网络代理服务，不知道有什么影响
> 
> 诡异的。所以您的登录成功，但项目获取失败。
> 
> 您是否尝试过使用新的 cookie 再次登录？

I just tried another cookies just before. It didn't work and showed same error

**Comment by liuss47** [comment]
> 如果您在浏览器中的 cookie 显示的项目多于“overleaf_session2”，例如 ，`overleaf_session2=...; oa=...; <key>=<value>`您只需将其`overleaf_session2=...`作为登录输入即可。

This do not work either.

**Comment by iamhyc** [comment]
I believe the problem should be related to your network environment. Please try to use other network connection or proxy to access `www.overleaf.com`.

**Comment by liuss47** [comment]
Hi there, Thanks a lot for your kind guidance. The problem solved after I retrid "https://www.overleaf.com". I guess I may mistakely  try "www.overleaf.com", though they are looks same after type in~
