### ISSUE TITLE
When I try to login with Cookie, I get the following error message given by the VS Code

### ISSUE THREAD

**Issue by Myerrs** [iamhyc/Overleaf-Workshop#30]
<img width="536" alt="Snipaste_2023-10-23_18-44-19" src="https://github.com/iamhyc/Overleaf-Workshop/assets/27666462/fa8baa64-0684-4597-9f34-34808949302b">

**Comment by Myerrs** [comment]
It is maybe the problem of version. Lowering the version seems to be a viable solution.

**Comment by iamhyc** [comment]
wait a minute, you mean the current version does not work?

**Comment by iamhyc** [comment]
I have tested with a fresh install of `v0.3.3`. Nothing wrong to me 😕

**Comment by iamhyc** [comment]
As there is no more feedback, I will close the issue now.

Please feel free to reopen or create new issues if your problem has not been solved.
