### ISSUE TITLE
[Feature Request] Plugin-support - Problems with virtual filesystem

### ISSUE THREAD

**Issue by LarsPROD** [iamhyc/Overleaf-Workshop#35]
Hi, 

this plugin is great! Me and my team are very amazed.

I would like to ask, if its possible to enable more plugin-compatibility? The most plugins we use are not suitible for files on a virtal filesystem.
The most important for us is a autoformatter, like provided in the common [LaTeX-workshop](https://marketplace.visualstudio.com/items?itemName=James-Yu.latex-workshop). But we use other extentions as well, wich have the same incompatibility.

best wishes,
Lars

**Comment by iamhyc** [comment]
The plugin compatibility with virtual file system is claimed by the plugin itself. So, unfortunately, we have nothing to do to improve this compatibility.

About code formatting, we are actually investigating the possibility with [unified-latex](https://github.com/siefkenj/unified-latex). We plan to provide the feature in/before version `v0.5.0`, please stay in tuned.

**Comment by LarsPROD** [comment]
yeah, i know, i hoped you were able to get a workaround done with a synced local copy or so :D 

Ah, that i didn`t know that, wonderful!

have thanks for the nice work!

**Comment by iamhyc** [comment]
> yeah, i know, i hoped you were able to get a workaround done with a synced local copy or so :D
> 
> Ah, that i didn`t know that, wonderful!
> 
> have thanks for the nice work!

Interesting idea. I will try to implement the "local syn copy" when I am getting on the "local git bridge" feature :)

**Comment by iamhyc** [comment]
@LarsPROD Hi, we have just released version `v0.4.2` which allow you to open project locally.
However, the function like "compile / pdf preview / intellisense" provided by overleaf server will not work any more on the local folder. Please refer to issue #36 for a more detailed guidance, and also give feedback on this function in that thread.

As for the code formatting function for virtual filesystem, it may still take some time and we have decided to postpone the release in version `v0.6.0`.

**Comment by iamhyc** [comment]
The format feature is now provided in version `v0.5.5`. I will close this issue as complete now.
