### ISSUE TITLE
[Feature Request]Use with LaTeX workshop

### ISSUE THREAD

**Issue by YijunYuan** [iamhyc/Overleaf-Workshop#36]
This extension has many wonderful features, but I'm familiar with using the LaTeX Workshop extension with `VSCode`, and local compiling and previewing is much faster. Is it possible to restrict the effect of this extension to only syncing the local file to the specific Overleaf project synchronously?

Currently, it can be done by editing locally-> syncing to the GitHub repo-> importing repo change to the Overleaf project, which is not so convenient.

**Comment by iamhyc** [comment]
Hi, we have just release `v0.4.2` which includes the "Local Replica" function.
Now you can open the project locally with "collaboration" enabled, while other functions like "preview, compile, intellisense" disabled.

To open the project locally, please right click on one of the overleaf project and click "Open Project Locally ..." as below.

![preview01](https://github.com/iamhyc/Overleaf-Workshop/assets/9068301/e192adc1-48f7-4b47-8b35-aac5300c5a96)

In the open local folder, you will see a "cloud" icon on the status bar where you can manage the local replica.

![preview02](https://github.com/iamhyc/Overleaf-Workshop/assets/9068301/94c7d6af-84fd-488b-97c7-058642bbbf97)

The current function may not be perfect cause I have not done a thorough test.
Please give us timely feedback so we can keep improve the function and finalize it in the future `v0.5.0`.

**Comment by YijunYuan** [comment]
> Hi, we have just release `v0.4.2` which includes the "Local Replica" function. Now you can open the project locally with "collaboration" enabled, while other functions like "preview, compile, intellisense" disabled.
> 
> To open the project locally, please right click on one of the overleaf project and click "Open Project Locally ..." as below.
> 
> ![preview01](https://user-images.githubusercontent.com/9068301/283995891-e192adc1-48f7-4b47-8b35-aac5300c5a96.png)
> 
> In the open local folder, you will see a "cloud" icon on the status bar where you can manage the local replica.
> 
> ![preview02](https://user-images.githubusercontent.com/9068301/283995811-94c7d6af-84fd-488b-97c7-058642bbbf97.png)
> 
> The current function may not be perfect cause I have not done a thorough test. Please give us timely feedback so we can keep improve the function and finalize it in the future `v0.5.0`.

OK, I have made a quick try. Most functions work perfectly. Here is a little thing:
Local LaTeX compile will produce temporary files, like `.log`, `.aux`, etc in the same folder as the main LaTeX source file, but I don't see them in the Overleaf project (browsed from the browser, of course). I guess that you are maintaining something like `.gitignore`. Am I correct?
On the other hand, the produced pdf file is synced to Overleaf, which behaves differently from using Overleaf directly, since the latter produces the pdf file in the special location. There is no perfect solution for this, for users can also upload a PDF intentionally to Overleaf.
If you are maintaining some kind of "exclusion list", maybe it can be exposed to the user.

**Comment by iamhyc** [comment]
You can configure the ignore patterns by: click the cloud icon --> local replica item --> "configure sync ignore patterns ..."
![](https://github.com/iamhyc/Overleaf-Workshop/assets/9068301/f23aff68-83b4-4505-ab7e-eb6b1994e42b)

The default rules only exclude the "main.pdf" and "output.pdf" files, you can add your own, and delete the already-synced pdf file manually.
![](https://github.com/iamhyc/Overleaf-Workshop/assets/9068301/e2985991-1fae-4fdc-a4ff-3e7a9591c4fe)

**Comment by YijunYuan** [comment]
> You can configure the ignore patterns by: click the cloud icon --> local replica item --> "configure sync ignore patterns ..." ![](https://user-images.githubusercontent.com/9068301/284003158-f23aff68-83b4-4505-ab7e-eb6b1994e42b.png)
> 
> The default rules only exclude the "main.pdf" and "output.pdf" files, you can add your own, and delete the already-synced pdf file manually on overleaf side. ![](https://user-images.githubusercontent.com/9068301/284003265-e2985991-1fae-4fdc-a4ff-3e7a9591c4fe.png)

That sounds great.

**Comment by YijunYuan** [comment]
Two things:
1. If I close the local replica window and reopen it, it fails to load:
<img width="146" alt="微信图片_20231119211214" src="https://github.com/iamhyc/Overleaf-Workshop/assets/7012463/05eead1d-4557-4fab-b6b3-377a015ff33b">
<img width="284" alt="微信图片_20231119211456" src="https://github.com/iamhyc/Overleaf-Workshop/assets/7012463/f952c5b1-c473-4277-bdc2-c84c55a6c00b">

2. The PDF viewer of LaTeX Workshop stopped working if I used it with Overleaf Workshop (the tab is blank).

**Comment by iamhyc** [comment]
> Two things:
> 
>     1. If I close the local replica window and reopen it, it fails to load:
> 
> 
> <img alt="微信图片_20231119211214" width="146" src="https://user-images.githubusercontent.com/7012463/284060043-05eead1d-4557-4fab-b6b3-377a015ff33b.png"> <img alt="微信图片_20231119211456" width="284" src="https://user-images.githubusercontent.com/7012463/284060187-f952c5b1-c473-4277-bdc2-c84c55a6c00b.png">

I have seen this on WSL. Are you using the extension inside WSL? if not, could you provide the original replica path?

> 
>     2. The PDF viewer of LaTeX Workshop stopped working if I used it with Overleaf Workshop (the tab is blank).

The pdf viewer register is a mess. Maybe you can disable and enable "Latex-Workshop" to see if it works

**Comment by YijunYuan** [comment]
> > Two things:
> > ```
> > 1. If I close the local replica window and reopen it, it fails to load:
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > <img alt="微信图片_20231119211214" width="146" src="https://user-images.githubusercontent.com/7012463/284060043-05eead1d-4557-4fab-b6b3-377a015ff33b.png"> <img alt="微信图片_20231119211456" width="284" src="https://user-images.githubusercontent.com/7012463/284060187-f952c5b1-c473-4277-bdc2-c84c55a6c00b.png">
> 
> I have seen this on WSL. Are you using the extension inside WSL? if not, could you provide the original replica path?
> 
> > ```
> > 2. The PDF viewer of LaTeX Workshop stopped working if I used it with Overleaf Workshop (the tab is blank).
> > ```
> 
> The pdf viewer register is a mess. Maybe you can disable and enable "Latex-Workshop" to see if it works

1. Yes I'm using it through WSL.
2. I will try it latter.

**Comment by iamhyc** [comment]
Noted. I will try to fix the WSL-related issue tomorrow.
I will also try to identify the existing illegal path and remove it in the records.

**Comment by iamhyc** [comment]
Hi, We have just released `v0.4.3` which includes the path parse fix.

I have tested the setup for 1) Windows, 2) Linux, 3) WSL virtual workspace, d) SSH virtual workspace (to Linux). Seems everything is working.

Please let me know if your problem is solved in `v0.4.3`.

**Comment by iamhyc** [comment]
Hi @YijunYuan , we have not heard your feedback for a long time.

If the function works in your use case, I will close this issue and prepare the release of `v0.5.0` soon.

**Comment by iamhyc** [comment]
The `v0.5.0` is released. I will now close this feature request as complete.
If you have any unresolved problems, please create new issue reports. Thank you!
