### ISSUE TITLE
[Feature Request]More pdf viewer bg color

### ISSUE THREAD

**Issue by rhfeiyang** [iamhyc/Overleaf-Workshop#38]
Can there be more background color for PDF viewing? The yellow color may be too bright while the black color will make the horizontal and vertical lines invisible.
If you can let the user define the color freely, that will be better.
And can you add the feature to remember the color selected? Every time I open the pdf viewer, it starts at white bg.

**Comment by iamhyc** [comment]
The theme color setting should have been stored, but apparently the resume does not work well now.
I will mark this as a bug report and fix it later.

As for other color scheme support, I am not sure whether it is necessary.

**Comment by rhfeiyang** [comment]
> The theme color setting should have been stored, but apparently the resume does not work well now. I will mark this as a bug report and fix it later.
> 
> As for other color scheme support, I am not sure whether it is necessary.

But yellow is too bright, while dark is not suitable for use unless the lines can be rendered normally...

**Comment by iamhyc** [comment]
@rhfeiyang Name the better hex color code for foreground/background color, I will give it a try.

The current dark theme colors are hard coded as below
https://github.com/iamhyc/Overleaf-Workshop/blob/2870232d351afc747f051b72d115363f8a2babaf/views/pdf-viewer/index.js#L13

**Comment by iamhyc** [comment]
@rhfeiyang I have fixed the restore issue and will release it with next version `v0.4.3`.

If you can come up with a better color theme today, I will also include the change in the release.

**Comment by rhfeiyang** [comment]
> @rhfeiyang I have fixed the restore issue and will release it with next version `v0.4.3`.
> 
> If you can come up with a better color theme today, I will also include the change in the release.

Now I use the bgColor of Dark theme as: "#4B4B4B", which I think is better than 1E1E1E
![image](https://github.com/iamhyc/Overleaf-Workshop/assets/99195158/fa79db8e-8c58-4f9b-8228-98cd8ce9054a)

After all, I hope the rendering problem of horizontal and vertical lines can be fixed.

**Comment by iamhyc** [comment]
Looks good to me, thanks for your help! The change has been included in the master branch, will release later.

As for the line rendering problem, it takes more work to be done, and I think it should be tracked in another issue #25 .

**Comment by iamhyc** [comment]
The `v0.4.3` has released. Please check.

Now the PDF viewer status (theme color, scale size) will be restored for each PDF file after re-open the workspace.
The default theme color is still the white-background one.

**Comment by rhfeiyang** [comment]
> The `v0.4.3` has released. Please check.
> 
> Now the PDF viewer status (theme color, scale size) will be restored for each PDF file after re-open the workspace. The default theme color is still the white-background one.

![image](https://github.com/iamhyc/Overleaf-Workshop/assets/99195158/aa2bb23d-9b45-4c32-a1c7-fa5c683d4105)

Well... It seems that the button to change the color disappeared.

**Comment by iamhyc** [comment]
Thanks for the notice! maybe something wrong with the extension packing, I will re-upload it.

**Comment by iamhyc** [comment]
ok, seems to be incompatible state, will fix it later today...

**Comment by iamhyc** [comment]
not a big problem, the fix is here ffbf91c1c60f7566d488f21d1c7e82b006ee85b3, will release it in `v0.5.0`.

**Comment by rhfeiyang** [comment]
> not a big problem, the fix is here [ffbf91c](https://github.com/iamhyc/Overleaf-Workshop/commit/ffbf91c1c60f7566d488f21d1c7e82b006ee85b3), will release it in `v0.5.0`.

I tried that. It works and seems better now.
