### ISSUE TITLE
Unable to compile file

### ISSUE THREAD

**Issue by Ahhj93** [iamhyc/Overleaf-Workshop#41]
I don't have a button to compile the file and therefore see the pdf

**Comment by iamhyc** [comment]
It automatically compiles when you open the project, or when you make any changes to the `.tex` file.

If you need to manually trigger the compile, you can use the shortcut `ctrl+alt+b` as below

![图片](https://github.com/iamhyc/Overleaf-Workshop/assets/9068301/4c19951e-df0a-4a19-b248-226e2f660d85)

**Comment by Ahhj93** [comment]
Ok thanks
