### ISSUE TITLE
Cannot get the project list

### ISSUE THREAD

**Issue by taiga4112** [iamhyc/Overleaf-Workshop#43]
I am an Overleaf Premium user. 
I can log in Overleaf on VSCode, but I cannot get the project list as attached figure.

![cannot_open](https://github.com/iamhyc/Overleaf-Workshop/assets/12507469/1d2115ea-f755-43f2-af52-e9ac67c9bbf4)

**Comment by taiga4112** [comment]
I have also a lot of Overleaf projects with multiple tags as attached.

 
<img width="538" alt="スクリーンショット 2023-11-30 23 06 58" src="https://github.com/iamhyc/Overleaf-Workshop/assets/12507469/9aa37446-14f7-4651-b6e6-236c5d539566">

**Comment by iamhyc** [comment]
![](https://github.com/iamhyc/Overleaf-Workshop/assets/9068301/c44e1497-e82e-4b36-a3d1-cacf3114e36c)

Hi, the above screenshot shows how we deal with tags now.
It is more like a folder and you can *move* the project in/out from the (tag) folder.

Currently you can only add one tag to one project in the extension, i.e., move the project under the tag.
If you want to add more than one tags, it is not supported and you have to refer to the webpage.

I am sorry about the inconvenience but I am afraid there is no way for vscode to display the tags alongside like the webpage.

The fix will be released in `v0.5.2` later today. Let me know if you have any good ideas, or I will release it on schedule :)

**Comment by taiga4112** [comment]
Hi, @iamhyc. Thank you for your contribution of this bugs.
I totally agree with your opinion.

**Comment by iamhyc** [comment]
Great! I will release it now and let's see if then you can get the project list.

**Comment by taiga4112** [comment]
Thanks. Now I can open my projects on VSCode using v0.5.2!!
