### ISSUE TITLE
Please add a command to focus in chat

### ISSUE THREAD

**Issue by jooyoungseo** [iamhyc/Overleaf-Workshop#45]
Type: <b>Feature Request</b>

Currently, there is no way to focus in chat by using the VSCode command palette. For keyboard-only users, please add a command to jump to the chat area.

Extension version: 0.5.1
VS Code version: Code - Insiders 1.85.0-insider (c6b48c364dde70c12bf977f1da50acda0fd801e3, 2023-11-30T05:35:40.559Z)
OS version: Windows_NT x64 10.0.22631
Modes:

**Comment by iamhyc** [comment]
Thanks for the suggestion. It is possible to make the chat area visible via command palette.

I will let you know when the feature is ready.
