### ISSUE TITLE
Extension doesn't reconnect to overleaf if network connection was interrupted

### ISSUE THREAD

**Issue by Matszwe02** [iamhyc/Overleaf-Workshop#46]
When I want to work on some project, it automatically updates data with overleaf and compiles documents. When I disconnect for a bit of time, then connect back, it loads endlessly. I can't compile the project and no changes are sent to overleaf. I have to restart vscode, and then it works again.

**Comment by iamhyc** [comment]
@Matszwe02 The fix is included in the latest version `v0.5.3`. Please help check if the problem is fixed on your side. Thank you!

**Comment by Matszwe02** [comment]
Thanks for the quick fix! I got it to work, but I saw that the file that was opened during this reconnection doesn't want to be saved. Every other file is saved, session with overleaf is opened, but this one file doesn't get saved. Check that out

**Comment by iamhyc** [comment]
> Thanks for the quick fix! I got it to work, but I saw that the file that was opened during this reconnection doesn't want to be saved. Every other file is saved, session with overleaf is opened, but this one file doesn't get saved. Check that out

![](https://github.com/iamhyc/Overleaf-Workshop/assets/9068301/dab1a0d6-ff1b-4d99-8d0e-26971c306b7d)

Ok ,I guess when you said "the file didn't get saved", you mean the file has a dot on the tab and you could not make things saved via `ctrl+s` or close the tab directly.

Please provide more details, better with demo figures/videos, so we can try to reproduce your situation. Thank you!

**Comment by iamhyc** [comment]
@Matszwe02 In the latest version `v0.5.4`, I have added the time out for saving file (and also other `socket.io` related function). Now it will ask you to retry when the timeout (3 seconds) is reached.

Please let me know if this is up to your expectation!

**Comment by Matszwe02** [comment]
Hi again. Thanks for the fix, it appears to be working perfectly now! Maybe the previous save issue is not always happening, but for now I'll say it's great. Thanks again!
