### ISSUE TITLE
[Accessibility] Consider using list view for Chat for improved accessibility

### ISSUE THREAD

**Issue by jooyoungseo** [iamhyc/Overleaf-Workshop#49]
Type: <b>Feature Request</b>

While the current Chat widget is  usable with screen reader, containing the Chat history within list view or tree view would be more accessible to keyboard-only users.

[`GitHub.copilot-chat`](https://marketplace.visualstudio.com/items?itemName=GitHub.copilot-chat) provides a really plasant navigation experience for both keyboard-only and screen reader users.

Extension version: 0.5.3
VS Code version: Code - Insiders 1.85.0-insider (94a3d7bac770b43ce97e9685715bef1a60d1a759, 2023-12-01T19:00:37.339Z)
OS version: Windows_NT x64 10.0.22631
Modes:

**Comment by iamhyc** [comment]
You are right. I just find the list cannot be navigated with keyboard. Will fix it.

**Comment by iamhyc** [comment]
Hi @jooyoungseo , in the latest release `v0.5.4`, you can navigate through the items with `Tab` (or `Shift+Tab`) key. I didn't handle the arrow keys, so it is still not a list view like "copilot chat". Besides, I also try to add the `aria-label` and `aria-selected` attributes. I hope this is a bit more helpful :)

**Comment by iamhyc** [comment]
Hi @jooyoungseo , I have tried to support arrow key (up/down) navigation, and add the attributes `aria-posinset` and `aria-setsize` to the message item. You can try the features in the attached temporary extension `v0.6.0-alpha`.
If it is up to your expectation, I will release it asap. Thanks for your help!

[overleaf-workshop-0.6.0-alpha.vsix.zip](https://github.com/iamhyc/Overleaf-Workshop/files/13691363/overleaf-workshop-0.6.0-alpha.vsix.zip)

**Comment by iamhyc** [comment]
The feature is included in the release `v0.6.0`. Please have a look at it.

I will close this issue as complete now. Please feel free to reopen or create new issue if you think the function is not completed.

**Comment by jooyoungseo** [comment]
@iamhyc Sorry for the delayed response. This works so nicely! Thanks for implementing this.
