### ISSUE TITLE
Changes are constantly reverted

### ISSUE THREAD

**Issue by Matszwe02** [iamhyc/Overleaf-Workshop#51]
As I'm creating a docment, the extension often doesn't send the changes that I made to the server, instead it rejects them, maing half of the changes disappear. I tried to work on this when using a stable network connection to ensure it wasn't caused by the previous bug.

**Comment by Matszwe02** [comment]
> Have done a quick check on my side with overleaf.com server, nothing wrong happened. Do you have other collaborators editing at the same time?

No, I'm the only collaborator. Most of the times it won't save, was when I switched to another app (I have save on lost focus in vscode), so maybe this lack of focus may have something to do with it?

**Comment by iamhyc** [comment]
> > Have done a quick check on my side with overleaf.com server, nothing wrong happened. Do you have other collaborators editing at the same time?
> 
> No, I'm the only collaborator. Most of the times it won't save, was when I switched to another app (I have save on lost focus in vscode), so maybe this lack of focus may have something to do with it?

Well, I also have that autosave enabled, should not be the case.

@QianrenLi Hi Qianren, could you spare some time help us checking if `v0.5.4` working properly?

**Comment by Matszwe02** [comment]
Ok, I think me being the only collaborator was a bit of oversimplification... I think the problem is, when I tried to drag and drop one file from another overleaf project, it just started adding more and more users to the collaboration, which are my clones.
![image](https://github.com/iamhyc/Overleaf-Workshop/assets/49353902/5a2d31c7-9f2e-44a6-8d80-d397e34b21ec)

**Comment by Matszwe02** [comment]
Try to drag and drop one tex file from one project to another one, because that creates this problem

**Comment by iamhyc** [comment]
> Try to drag and drop one tex file from one project to another one, because that creates this problem

It basically not supported to move/copy file between projects, but the aftereffect should not be this fatal ...
Hold on, let me give it a try.

**Comment by iamhyc** [comment]
> Try to drag and drop one tex file from one project to another one, because that creates this problem

Hi @Matszwe02 , I plan to simply forbid this operation for now, i.e., the "rename/move/copy" operation across "servers/projects/users" will not be allowed.

But I wonder if your original problem is related to this bug. Let me know if you find more details.

**Comment by Matszwe02** [comment]
> BTW, if you do not move files between projects, should it be okay to save files?

Yes, I'm downloading them and uploading on the second project. And the original problem I think is related to this bug, so I think this issue ticket is relavant

**Comment by iamhyc** [comment]
> > BTW, if you do not move files between projects, should it be okay to save files?
> 
> Yes, I'm downloading them and uploading on the second project. And the original problem I think is related to this bug, so I think this issue ticket is relavant

I see. As a workaround, please download the first-project file to local disk, then drag-and-drop it to your second-project. This is achievable.

I fill try to figure out a better solution to support this direct move/copy between projects.

**Comment by iamhyc** [comment]
[overleaf-workshop-0.5.5-alpha.zip](https://github.com/iamhyc/Overleaf-Workshop/files/13601670/overleaf-workshop-0.5.5-alpha.zip)

Hi @Matszwe02 , I just package a temporary extension with this fix 8cafb87fbb7481ab29c551953b028fe7c36032a0 included. You can have a try :)

**Comment by Matszwe02** [comment]
Hi again. I managed to break it (also duplicated my overleaf client) without doing that mistake like earlier. I dragged and dropped an image into vscode (which worked) and wrote a few paragraphs, then I saw what I have 2 clones of myself. For now I'm still trying to figure out what breaks this extension, but I want to let you know what happened. I was operating on the vscode store version of the extension, now I've installed the howfix and I'll check if the issue persists

**Comment by Matszwe02** [comment]
Just tested it. I didn't paste anything, maybe there was one reconnect, and there is a new clone. Now I tested it and for sure one clone is added everytime a network connection is reset, so there's a bug in your reconnection feature, I think

**Comment by iamhyc** [comment]
> Just tested it. I didn't paste anything, maybe there was one reconnect, and there is a new clone. Now I tested it again and for sure one clone is added everytime a network connection is reset, so there's a bug in your reconnection feature, I think

The reconnection happened only when `disconnected` event is triggered. I wonder if you can see the same clone on the webpage. If that is the case, the "clone" is just a dangling connection recorded at the server side. Otherwise it should related to "a bug in the reconnection feature".

**Comment by Matszwe02** [comment]
When I move my cursor, all these users move with me, when looking at the colored cursors in vscode

**Comment by iamhyc** [comment]
> When I move my cursor, all these users move with me, when looking at the colored cursors in vscode

That is weird. I will try to reproduce the situation.

**Comment by iamhyc** [comment]
[overleaf-workshop-0.5.5-alpha2.vsix.zip](https://github.com/iamhyc/Overleaf-Workshop/files/13634301/overleaf-workshop-0.5.5-alpha2.vsix.zip)

@Matszwe02 @rhfeiyang Hi, I find the cause for follow-up color cursors after re-connect, but I cannot trigger the reconnect situation in my environment.

I have packed another temporary version `0.5.5-alpha2` as attached. Please let me know if the problem is fixed or not. Thank you!

**Comment by Matszwe02** [comment]
I think it doesn't reconnect at all now
![image](https://github.com/iamhyc/Overleaf-Workshop/assets/49353902/5c159798-006c-4492-a1fb-e14653ae894a)

**Comment by iamhyc** [comment]
> I think it doesn't reconnect at all now

The `Connection lost` error is thrown, so the maximum retries (3 times) is reached.
There should also be a popup window ask you to reload the window.

**Comment by Matszwe02** [comment]
> Owner

It wasn't there. There should be a red icon at the bottom to notify that connection is lost and clicking on it retries it

**Comment by iamhyc** [comment]
Hi @QianrenLi , could you have a look at it? I think the root cause has been revealed.

**Comment by rhfeiyang** [comment]
> I think it doesn't reconnect at all now ![image](https://private-user-images.githubusercontent.com/49353902/289897003-5c159798-006c-4492-a1fb-e14653ae894a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIzOTM1MjEsIm5iZiI6MTcwMjM5MzIyMSwicGF0aCI6Ii80OTM1MzkwMi8yODk4OTcwMDMtNWMxNTk3OTgtMDA2Yy00NDkyLWExZmItZTE0NjUzYWU4OTRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEyVDE1MDAyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc3NTdiYTNlOWVhNTQ1YmU0NzZiYzE3NjI3YzAyZjAxZGZhOWY3ZGQ0MDBmYWVkYTkwYjE2M2YzZmJiZDg3NmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.oCYOPuAUy2LOWu95ExG2WPkPprH5hRNLowC39OT5F1I)

In my case, it seems working well. Do you ensure the network really connects to Overleaf then? I remember I also had a similar problem until I set all the unknown web domains to go through the proxy.

**Comment by Matszwe02** [comment]
I was using a normal network connection, so it should be able to connect to overleaf.com. I'll try to reproduce this issue, maybe there was something off with it that time

> > I think it doesn't reconnect at all now ![image](https://private-user-images.githubusercontent.com/49353902/289897003-5c159798-006c-4492-a1fb-e14653ae894a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIzOTM1MjEsIm5iZiI6MTcwMjM5MzIyMSwicGF0aCI6Ii80OTM1MzkwMi8yODk4OTcwMDMtNWMxNTk3OTgtMDA2Yy00NDkyLWExZmItZTE0NjUzYWU4OTRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEyVDE1MDAyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc3NTdiYTNlOWVhNTQ1YmU0NzZiYzE3NjI3YzAyZjAxZGZhOWY3ZGQ0MDBmYWVkYTkwYjE2M2YzZmJiZDg3NmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.oCYOPuAUy2LOWu95ExG2WPkPprH5hRNLowC39OT5F1I)
> 
> In my case, it seems working well. Do you ensure the network really connects to Overleaf then? I remember I also had a similar problem until I set all the unknown web domains to go through the proxy.

**Comment by QianrenLi** [comment]
Hi, @Matszwe02, I manually disconnect and found that under `alpha2`, it seems the cursor do not replicated itself. And for your problem, to me it seems to be an issue related to the network and please provide more information about how to reproduce it thus we can found out what happens.

**Comment by Matszwe02** [comment]
> Hi, @Matszwe02, I manually disconnected from server and found that under `alpha2`, it seems that the cursor does not replicated itself. And for your problem, to me it seems to be an issue related to the network and please provide more information about how to reproduce it thus we can found out what happens.

I'll try to reproduce it myself first, I think it happened when I put my pc to sleep for a bit

**Comment by Matszwe02** [comment]
I was able to reproduce the issue. I disconnected from wifi, reconnected after a while to a different wifi and discarded the lost connection message. After that, there's no way of connecting back.
https://github.com/iamhyc/Overleaf-Workshop/assets/49353902/dd6f31bc-20d1-42e6-a5a4-a3949c27b0fd

**Comment by iamhyc** [comment]
> I was able to reproduce the issue. I disconnected from wifi, reconnected after a while to a different wifi and discarded the lost connection message. After that, there's no way of connecting back.

If you ignore the "reload button", yes, there is no way to connect any more.
I have fixed it but not packed in the last alph2 version. Here I attach the `v0.5.5-alpha3` to reflect all changes in fix 9c313b3cd5314ea5060a6781aa29cd15bfc10949.
It would allow you to manually try writing/reading even it have required you to reload the window.

[overleaf-workshop-0.5.5-alpha3.vsix.zip](https://github.com/iamhyc/Overleaf-Workshop/files/13679741/overleaf-workshop-0.5.5-alpha3.vsix.zip)

**Comment by Matszwe02** [comment]
> > I was able to reproduce the issue. I disconnected from wifi, reconnected after a while to a different wifi and discarded the lost connection message. After that, there's no way of connecting back.
> 
> If you ignore the "reload button", yes, there is no way to connect any more. I have fixed it but not packed in the last alph2 version. Here I attach the `v0.5.5-alpha4` to reflect all changes in fix ~[9c313b3](https://github.com/iamhyc/Overleaf-Workshop/commit/9c313b3cd5314ea5060a6781aa29cd15bfc10949)~ [8fd39ce](https://github.com/iamhyc/Overleaf-Workshop/commit/8fd39ce3652426b8099c009ff665e31e9eefd3ec). It would allow you to manually try writing/reading even it have required you to reload the window.
> 
> [overleaf-workshop-0.5.5-alpha4.vsix.zip](https://github.com/iamhyc/Overleaf-Workshop/files/13683406/overleaf-workshop-0.5.5-alpha4.vsix.zip)

I don't know if that was in your mind, but I would have an option to click this "not connected" icon (as in the video), to reconnect to the overleaf server

**Comment by iamhyc** [comment]
> > > I was able to reproduce the issue. I disconnected from wifi, reconnected after a while to a different wifi and discarded the lost connection message. After that, there's no way of connecting back.
> > 
> > 
> > If you ignore the "reload button", yes, there is no way to connect any more. I have fixed it but not packed in the last alph2 version. Here I attach the `v0.5.5-alpha4` to reflect all changes in fix ~[9c313b3](https://github.com/iamhyc/Overleaf-Workshop/commit/9c313b3cd5314ea5060a6781aa29cd15bfc10949)~ [8fd39ce](https://github.com/iamhyc/Overleaf-Workshop/commit/8fd39ce3652426b8099c009ff665e31e9eefd3ec). It would allow you to manually try writing/reading even it have required you to reload the window.
> > [overleaf-workshop-0.5.5-alpha4.vsix.zip](https://github.com/iamhyc/Overleaf-Workshop/files/13683406/overleaf-workshop-0.5.5-alpha4.vsix.zip)
> 
> I don't know if that was in your mind, but I would have an option to click this "not connected" icon (as in the video), to reconnect to the overleaf server

I don't know what you are talking about "option", but please first try "0.5.5-alpha4" above and let met know if you can read the file even the "reload button" appeared.

**Comment by Matszwe02** [comment]
Ok, it appears to be working now, but I'm now testing it turning on and off my wifi, but the read test will come when I'll be using it in the longer period of time. But I think for now it's working and we can close this issue

**Comment by iamhyc** [comment]
Thank you! Please feel free to fire the issue if you encounter any new problem.
