### ISSUE TITLE
Error in "Open Project in New Window" 

### ISSUE THREAD

**Issue by QianrenLi** [iamhyc/Overleaf-Workshop#6]
When use "Open Project in New Window", window poped out do not contain the project and only shows an empty window

![2023-09-02 16-59-05 的屏幕截图](https://github.com/iamhyc/Overleaf-Workshop/assets/51881852/9eb96237-d475-45f1-a6ce-c3c076f8b79e)

**Comment by iamhyc** [comment]
It should be fixed now on the `master` branch. Please check.
