### ISSUE TITLE
[Feature Request]  Add auto-completion popups (IntelliSense) for references in .bib files when typing \cite{...}

### ISSUE THREAD

**Issue by elyurn** [iamhyc/Overleaf-Workshop#61]
### Motivation
> Please give strong enough reason(s) why the feature is demanded.
- An equivalent of this feature is available in Overleaf Webpage!

### Feature Description
> A clear and concise description of what you want to happen under what circumstance.
- **Would it be possible to add an auto-completion popup when using the command \cite{...}, loading references from .bib files contained in the project?**

Thanks!

**Comment by iamhyc** [comment]
Hi @elyurn , the reference completion is provided via the `\bibitem` items in `.output/output.bbl` file, which means you need to compile the project firstly and expect the completion to work.

**Comment by iamhyc** [comment]
> Hi @iamhyc, thanks for the info. The thing is that I would like to have access to the completion for references that are not already cited in the .tex file. Can't we read directly all the entries in bib files or perform an action in the background to access them?

You are right. I will mark it again as a feature request.

@QianrenLi Hi Qianren, if you have time, please have a look at it.

**Comment by iamhyc** [comment]
The feature is now available in the release of `v0.9.0`, which is contributed and verified by @QianrenLi . Thanks for his continuous support and improvement 🎉

**Comment by elyurn** [comment]
Amazing! Thank you so much @QianrenLi & @iamhyc!
