### ISSUE TITLE
[Feature Request] Make failing log message more prominent

### ISSUE THREAD

**Issue by pfuhlert** [iamhyc/Overleaf-Workshop#63]
### Disclaimer
- [x] The request feature has not been addressed in the [feature request list](https://github.com/iamhyc/Overleaf-Workshop/issues?q=is%3Aissue+label%3A%22feature+request%22+).
- [x] The design of the feature does not require detailed discussion, or existing discussion with drawn conclusion can be found in [Discussions Area](https://github.com/iamhyc/Overleaf-Workshop/discussions) at: [paste the link here]

### Motivation
When compiling fails, it is hard to see the log message right away. It is highlighted in the code with the squiggly lines (which is cool), but when I do not know where it fails it is hard to see. So right now I usually go to overleaf.com and look at the website.

### Feature Description
The suggested feature would make this more prominent. One approach would be to add the logfile to the Output view of vscode.

**Comment by iamhyc** [comment]
You can find all the errors (and warnings) in the Problems panel.

![](https://github.com/iamhyc/Overleaf-Workshop/assets/9068301/a3fe33ba-e785-42eb-8e2d-c5df34477946)

**Comment by pfuhlert** [comment]
Sorry I had the impression that some errors were shown as warnings here, but I cannot reproduce it right now. Thank you.
