### ISSUE TITLE
Cannot logout from server, or login into another one

### ISSUE THREAD

**Issue by Matszwe02** [iamhyc/Overleaf-Workshop#68]
I wont guess your situation anymore. Do as follows:

- right click on all the servers and remove them
- there will always be a default *unlogged-in* server once you have the list emptied, dont panic
- browse the home page of overleaf in browser, and extract the cookie
- login with the cookie in the extension

if you still fail and want to reset the extension, please seek for information on how to reset vscode globalStorage on internet.

_Originally posted by @iamhyc in https://github.com/iamhyc/Overleaf-Workshop/issues/65#issuecomment-1879750979_

**Comment by Matszwe02** [comment]
https://github.com/iamhyc/Overleaf-Workshop/assets/49353902/d3c62264-76cd-472d-affb-1536f11c9c3d

**Comment by Matszwe02** [comment]
ok, I just found out that the "default server address" isn't applied out of the box, I had to type it manually

**Comment by Matszwe02** [comment]
and I still cannot login to the next server or logout from this one

**Comment by Matszwe02** [comment]
cannot login either with password and cookies.

There's an error when logging in with cookies:
![image](https://github.com/iamhyc/Overleaf-Workshop/assets/49353902/84192f9e-e7be-478d-ad46-7a85e7ff3376)

**Comment by Matszwe02** [comment]
Here's all what I tried:

https://github.com/iamhyc/Overleaf-Workshop/assets/49353902/ba260a1a-b7a6-4719-b04e-800592ab95c1

**Comment by Matszwe02** [comment]
removing overleaf-workshop entry from vscode db helped, and now I can log in, but please, could you figure out why it wasn't working, so the extension will be self-repairing in case of any fatal issue?
![image](https://github.com/iamhyc/Overleaf-Workshop/assets/49353902/bbe88818-7564-46fa-bc01-de4fdade1854)

here's the db dump:
```json
iamhyc.overleaf-workshop{"overleaf-servers":{"www.overleaf.com":{"name":"www.overleaf.com","url":"https://www.overleaf.com/","login":{"userId":"653cffe62a47cc70d3c25c43","username":"wiegdyczzzvysexuem@ckptr.com","identity":{"cookies":"overleaf_session2=mypreciouscookiethathasnothingtodowiththisissue; GCLB=CJOL_4v5pNmQFQ","csrfToken":"pN9FfKYo-jN0nO9WsueOhyrQEm4YF4P6Wtxc"},"projects":[{"id":"657dc345a3d5e3bb3c0be799","name":"sensoryka L7","lastUpdated":"2023-12-16T15:34:33.658Z","lastUpdatedBy":{"id":"6375f6778f6cad7914d4c4f7","email":"275778@student.pwr.edu.pl","firstName":"275778","lastName":""},"accessLevel":"readWrite","source":"invite","archived":false,"trashed":false,"owner":{"id":"6375f6778f6cad7914d4c4f7","email":"275778@student.pwr.edu.pl","firstName":"275778","lastName":""},"userId":"653cffe62a47cc70d3c25c43"},{"id":"6571a2565e3268535e537701","name":"Sensoryka CHEM","lastUpdated":"2023-12-15T14:20:43.360Z","lastUpdatedBy":{"id":"653cffe62a47cc70d3c25c43","email":"wiegdyczzzvysexuem@ckptr.com","firstName":"wiegdyczzzvysexuem","lastName":""},"accessLevel":"owner","source":"owner","archived":false,"trashed":false,"owner":{"id":"653cffe62a47cc70d3c25c43","email":"wiegdyczzzvysexuem@ckptr.com","firstName":"wiegdyczzzvysexuem","lastName":""},"userId":"653cffe62a47cc70d3c25c43"},{"id":"656b6b10a94733eee855834d","name":"sensoryka L2 (Copy)","lastUpdated":"2023-12-04T20:00:28.189Z","lastUpdatedBy":{"id":"653cffe62a47cc70d3c25c43","email":"wiegdyczzzvysexuem@ckptr.com","firstName":"wiegdyczzzvysexuem","lastName":""},"accessLevel":"readWrite","source":"invite","archived":false,"trashed":false,"owner":{"id":"6375f6778f6cad7914d4c4f7","email":"275778@student.pwr.edu.pl","firstName":"275778","lastName":""},"userId":"653cffe62a47cc70d3c25c43"},{"id":"656b7063507b6e6ecb9761b0","name":"Sensoryka ALKO","lastUpdated":"2023-12-02T21:03:46.499Z","lastUpdatedBy":{"id":"653cffe62a47cc70d3c25c43","email":"wiegdyczzzvysexuem@ckptr.com","firstName":"wiegdyczzzvysex
```

**Comment by iamhyc** [comment]
please squash your feedback in to a standard bug report *logically*. I believe you can do that. Thank you in advance!

**Comment by iamhyc** [comment]
To avoid us waste another day on this meaningless cross-timezone emotional *interaction*, please help me verify my thoughts I came up in my dream.

1. reset all you can reset
2. login normally with cookie
3. logout from the browser (to emulate the expiration cookie)
4. then try to logout from extension and see if that is what you suffered from.

Thank you.

**Comment by iamhyc** [comment]
apparently not, just tested meaninglessly on my side.

![](https://github.com/iamhyc/Overleaf-Workshop/assets/9068301/726a24d2-1230-46f7-994d-09beebbeba60)

If you can read the code, the login information is removed anyway regardless of the success of logout or not.

That is to say, nothing related to logout, unless you ***stuck*** in waiting for HTTP response. Also check your network please.
