### ISSUE TITLE
How to get 'overleaf server address'?

### ISSUE THREAD

**Issue by LiuWenJia-ops** [iamhyc/Overleaf-Workshop#7]
From the example in gif, it seems like the editing share link? I dont have my overleaf project on a private server.

**Comment by iamhyc** [comment]
The server address is exactly the web address to your private server, e.g., "http://overleaf.org".

Remind it should start with "http://" or "https://", or an error will be raised.

**Comment by LiuWenJia-ops** [comment]
Still cant get the point. I cannt find a link like this below, with personalized suffix and port number.
<img width="643" alt="image" src="https://github.com/iamhyc/Overleaf-Workshop/assets/31568487/41915c40-9855-4082-a13c-7775cd7f0145">

I only have my project link like: `https://www.overleaf.com/project/xxxxxxxxxxx` 

and 'Anyone with this link can edit this project' like `https://www.overleaf.com/xxxxxxxxxxxxxxxxxxxxxx`

**Comment by iamhyc** [comment]
> I only have my project link like: https://www.overleaf.com/project/xxxxxxxxxxx

> and 'Anyone with this link can edit this project' like https://www.overleaf.com/xxxxxxxxxxxxxxxxxxxxxx

Given your share link or project link, the server address is `https://www.overleaf.com`

> Again, I dont have my overleaf project on a private server.

Sorry, we currently only support self-hosted open-source overleaf server. Please check the "Compatibility" section on README. This project is still in start stage and only `sharelatex/sharelatex:3.5.11` (the version I used) is verified.

The login to `overleaf.com` or similar sites with captcha enabled is hard, and we have to display the original login page to user in a webview panel.

Anyway, I will put this request in plan. Please stay in tuned!
