### ISSUE TITLE
Compile the Project failed in mac 

### ISSUE THREAD

**Issue by gobs-code** [iamhyc/Overleaf-Workshop#77]
### Describe the bug
The instructions of Ctrl+Option (Alt)+B and Ctrl+Option(Alt)+V  do not work on Mac.

**Comment by iamhyc** [comment]
Hi, I don't have a Mac but I see we do have a typo in `package.json` for view keybindings

https://github.com/iamhyc/Overleaf-Workshop/blob/5f0890b376041c6683c8780f6f6fd8aa46b799c1/package.json#L363

I think there is no problem with `cmd+alt+b`. Please try the auto-generated extension below and see if it works now:

https://github.com/iamhyc/Overleaf-Workshop/actions/runs/7516848901?pr=78
