### ISSUE TITLE
Cannot remove server

### ISSUE THREAD

**Issue by jooyoungseo** [iamhyc/Overleaf-Workshop#80]
Type: <b>Bug</b>

Since my session cookie expired, I wanted to sign in again to my Overleaf host. However, I could not remove the existing server. I reinstalled the extension entirely multiple times, but that did not resolve the issue.

![Recording 2024-01-16 at 20 43 52](https://github.com/iamhyc/Overleaf-Workshop/assets/19754711/7a464517-e1cd-4cff-8ea9-a9b363edbe0d)

Extension version: 0.8.0
VS Code version: Code - Insiders 1.86.0-insider (2c8f29174a63b3ace3d00ad0028cdc7ed9853b8b, 2024-01-16T05:35:26.709Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz (8 x 2611)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.71GB (2.28GB free)|
|Process Argv|--crash-reporter-id b05b88e5-8894-4031-ae34-fa034ebddea9|
|Screen Reader|yes|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vscod805cf:30301675
vsaa593:30376534
py29gd2263:30784851
vsclangdf:30492506
c4g48928:30535728
a9j8j154:30646983
pythongtdpath:30726887
i26e3531:30792625
welcomedialog:30812478
pythonidxpt:30768918
pythonnoceb:30776497
asynctok:30898717
dsvsc013:30777762
dsvsc014:30777825
dsvsc015:30821418
pythontestfixt:30866404
pythonregdiag2:30926734
pyreplss1:30879911
pythonmypyd1:30859725
pythoncet0:30859736
pythontbext0:30879054
accentitlementst:30870582
dsvsc016:30879898
dsvsc017:30880771
dsvsc018:30880772

```

</details>

**Comment by jooyoungseo** [comment]
@iamhyc -- I found the issue. I had to click "Yes" button to confirm the removal of the server. However, the notification was not alerted via aria and I did not recognize the prompt as a screen reader user. Could you please improve its accessibility just like the one you implemented in "No collaborator found" warning?

**Comment by iamhyc** [comment]
Noted. I will try to improve it.

**Comment by iamhyc** [comment]
Hi @jooyoungseo , please help check if the experience is better in the latest release of `v0.8.1`.

I have changed all the *silent* information message boxes to warning/error message boxes.

**Comment by jooyoungseo** [comment]
@iamhyc -- thanks. It works well! BTW, I currently hear "Error" prefix in the confirmation alert when removing a server. Could we try with warning instead of error? Do you want me to communicate directly with VSCode team regarding the silent alert issue? May I ask what alert you originally used?

**Comment by iamhyc** [comment]
@jooyoungseo Thanks for the feedback!.  I thought the "error message" could highlight the severity, but the "error prefix" is definitely not what we want. I will replace the errors with warnings in the next release.

As for the "silent alert" messages, they are created using the `showInformationMessage` function and I am not sure if the information-level messages are made silent on purpose. Now I only use `showWarningMessage`/`showErrorMessage` to create warning/error-level messages.
