### ISSUE TITLE
Unexpected input-lag on intel-based Mac

### ISSUE THREAD

**Issue by hy-zhao23** [iamhyc/Overleaf-Workshop#84]
### Describe the bug
> On Intel-based Mac, input has unbearable lag. Actually, on my M-based mac, it is not as fast as expect either but it doesn't affect work efficiency. I've tested that edit plain text in VSCode does not have the same problem.

### Environment
 - **Overleaf Workshop Extension version**: 0.8.1
 - **VS Code version**: 1.85.1
 - **Overleaf Edition**: Official (Server Pro)

**Comment by iamhyc** [comment]
I don't have a MAC to reproduce your situation, but I think you could provide more information so we can try to figure out the cause. Here are some suggestions:
1. Disable other VS Code extensions and see if it works.
2. Is there any abnormal CPU usage or network throughput when typing?
3. If the spell check is disabled, is it better?
4. Does the lag exists in a small example project?

**Comment by iamhyc** [comment]
> Hi,
> 
> Thank you for reply!
> 
> Here is the answer to your questions:
> 
>     1. I downloaded a latex project locally and did not disable any extensions. It turned out that everything works fine. But when I switch to projects from overleaf workshop the lag happened again.

Please firstly disable the other extensions to make sure they do not cause problems.

>     2. I am sorry that I am not quite familiar with this.

I found macOS has [Activity Monitor](https://support.apple.com/guide/activity-monitor/welcome/mac). You can check if VS Code takes too many CPU when you are typing.

>     3. Maybe it is not the problem of spell check from what i got in the first question.

>     4. Yes, it is only a conference paper.

I mean, you can try with the example project template provided by Overleaf.

![](https://github.com/iamhyc/Overleaf-Workshop/assets/9068301/f75120a2-38c0-4786-a93f-26217029bc98)

**Comment by hy-zhao23** [comment]
Thank you! I found one extension has caused the delay. I will close this issue.
