### ISSUE TITLE
[Feature Request] Manual compile selection

### ISSUE THREAD

**Issue by rhfeiyang** [iamhyc/Overleaf-Workshop#85]
### Disclaimer
> Please make sure all the items below is checked (i.e., prefixed with "- [x]")
- [x ] The request feature has not been addressed in the [feature request list](https://github.com/iamhyc/Overleaf-Workshop/issues?q=is%3Aissue+label%3A%22feature+request%22+).
- [x ] The design of the feature does not require detailed discussion, or existing discussion with drawn conclusion can be found in [Discussions Area](https://github.com/iamhyc/Overleaf-Workshop/discussions) at: [paste the link here]

### Motivation
> Please give strong enough reason(s) why the feature is demanded.
- The current compile model is auto compile immediately after any changes. But overleaf.com compiles very slowly. I often meet the problem that the compiled result is the old one but the new one will not compile. For example, when I type "How are you", it is likely to have the compiled result with "How", but w/o "are you" after a long waiting, which is annoying. Besides, the overleaf.com often fails because of frequently re-compile request.

### Feature Description
> A clear and concise description of what you want to happen under what circumstance.

- Enable manual compile selection, such as compile after "ctrl+s" which may be better. This way, the overleaf will only compile when the user needs it.

### [Optional] Additional context
> Please strike out any inappropriate items below. If you are not aware of the difference, please ignore this section.
- **Applicable Overleaf Edition**: Official / Community / Enterprise (Server Pro)
- **Applicable Extension Range**: Desktop Extension / Web Extension

**Comment by iamhyc** [comment]
Please try to disable the "compile on save" feature in the settings.

![](https://github.com/iamhyc/Overleaf-Workshop/assets/9068301/fbf982f0-87d0-4a87-838a-b9b79e58f9a2)

**Comment by rhfeiyang** [comment]
> Please try to disable the "compile on save" feature in the settings.
> 
> ![](https://private-user-images.githubusercontent.com/9068301/298062566-fbf982f0-87d0-4a87-838a-b9b79e58f9a2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2NjcwMTMsIm5iZiI6MTcwNTY2NjcxMywicGF0aCI6Ii85MDY4MzAxLzI5ODA2MjU2Ni1mYmY5ODJmMC04N2QwLTRhODctODM4YS1iOWI3OWU1OGY5YTIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDExOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMTlUMTIxODMzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDFkMjM1YmI2Yjg0MzJjMDc4NTBkYzBiZTlkYjMxNjM0YWRhNzJiOTUyMTcyYjJiMjVjZmQ1MzZlNTU0Y2M4ZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ._I8GYkdAgmtTb0e3lCTE5l3IBkFuUddO16V41MIByto)

But this will just not compile until I click the compile selection button.
![image](https://github.com/iamhyc/Overleaf-Workshop/assets/99195158/2ff253b6-6409-40db-8c20-40c19b484353)

This is very convenient. I just want it to compile when I save, not compile when I start change.

**Comment by iamhyc** [comment]
The manual compile shortcuts is `ctrl+alt+B`.

The "compile selection" is used to change the compiler, while also trigger compile once after the change.

**Comment by rhfeiyang** [comment]
> The manual compile shortcuts is `ctrl+alt+B`.
> 
> The "compile selection" is used to change the compiler, while also trigger compile once after the change.

OK, thank you.
