### ISSUE TITLE
I can't connect to the overleaf server using token ?

### ISSUE THREAD

**Issue by securitylab-repository** [iamhyc/Overleaf-Workshop#96]
### Describe the bug
> A clear and concise description of what the bug is.

### Expected behavior
> A clear and concise description of what you expected to happen.

### How To Reproduce
> Detailed steps to reproduce the behavior.

### Environment
 - **Overleaf Workshop Extension version**: [e.g., 0.7.0]
 - **VS Code version**: [e.g. 1.85.0]
 - **Overleaf Edition**: Official / Community / Enterprise (Server Pro)

### [Optional] Developer Logs
> If applicable, please paste the logs inside the details section below.
> Please find the logs via: Title bar **"Help"** > **"Toggle Developer Tools"** > **"Console"**.

<details>
  ...
</details>

**Comment by iamhyc** [comment]
Please try to provide more context information instead leaving the issue template empty.

**Comment by iamhyc** [comment]
Since there is no more information provided, I will close it now.
